In [2]:
import pandas as pd 
import numpy as np

In [3]:
model = pd.read_csv("../../../data/raw/depmap/Model.csv")
model

,ModelID,PatientID,CellLineName,StrippedCellLineName,DepmapModelType,OncotreeLineage,OncotreePrimaryDisease,OncotreeSubtype,OncotreeCode,PatientSubtypeFeatures,...,PublicComments,CCLEName,HCMIID,PediatricModelType,ModelAvailableInDbgap,ModelSubtypeFeatures,WTSIMasterCellID,SangerModelID,COSMICID,ModelIDAlias
0,ACH-000001,PT-gj46wT,NIH:OVCAR-3,NIHOVCAR3,HGSOC,Ovary/Fallopian Tube,Ovarian Epithelial Tumor,High-Grade Serous Ovarian Cancer,HGSOC,NaN,...,NaN,NIHOVCAR3_OVARY,NaN,False,Approved for public sharing - CCLE,NaN,2201.0,SIDM00105,905933.0,NaN
1,ACH-000002,PT-5qa3uk,HL-60,HL60,AMLMRC,Myeloid,Acute Myeloid Leukemia,AML with Myelodysplasia-Related Changes,AMLMRC,"TP53(del), CDKN2A and NRAS mutations [PubMed=2...",...,NaN,HL60_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE,NaN,True,Approved for public sharing - CCLE,"NRAS, BCOR and CDKN2A",55.0,SIDM00829,905938.0,NaN
2,ACH-000003,PT-puKIyc,CACO2,CACO2,COAD,Bowel,Colorectal Adenocarcinoma,Colon Adenocarcinoma,COAD,NaN,...,NaN,CACO2_LARGE_INTESTINE,NaN,False,Approved for public sharing - CCLE,NaN,NaN,SIDM00891,NaN,NaN
3,ACH-000004,PT-q4K2cp,HEL,HEL,AMLNOS,Myeloid,Acute Myeloid Leukemia,"AML, NOS",AMLNOS,JAK2 and TP53 mutations,...,NaN,HEL_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE,NaN,True,Approved for public sharing - CCLE,JAK2 and TP53,783.0,SIDM00594,907053.0,NaN
4,ACH-000005,PT-q4K2cp,HEL 92.1.7,HEL9217,AML,Myeloid,Acute Myeloid Leukemia,Acute Myeloid Leukemia,AML,JAK2 and TP53 mutations,...,NaN,HEL9217_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE,NaN,True,Approved for public sharing - CCLE,NaN,NaN,SIDM00593,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2127,ACH-003473,PT-fG5tCh,CCLF_PEDS_0013_T,CCLFPEDS0013T,ERMS,Soft Tissue,Rhabdomyosarcoma,Embryonal Rhabdomyosarcoma,ERMS,NaN,...,NaN,NaN,HCM-BROD-0006-C49,True,NaN,NaN,NaN,NaN,NaN,NaN
2128,ACH-003474,PT-WxfjG3,CCLF_HNSC_0001_T,CCLFHNSC0001T,HNSC,Head and Neck,Head and Neck Squamous Cell Carcinoma,Head and Neck Squamous Cell Carcinoma,HNSC,NaN,...,NaN,NaN,HCM-BROD-1131-C06,False,NaN,NaN,NaN,NaN,NaN,NaN
2129,ACH-003475,PT-ce6oqw,CCLF_HNSC_0003_T,CCLFHNSC0003T,HNSC,Head and Neck,Head and Neck Squamous Cell Carcinoma,Head and Neck Squamous Cell Carcinoma,HNSC,NaN,...,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN
2130,ACH-003476,PT-ce6oqw,CCLF_HNSC_0002_T,CCLFHNSC0002T,ESCC,Esophagus/Stomach,Esophageal Squamous Cell Carcinoma,Esophageal Squamous Cell Carcinoma,ESCC,NaN,...,NaN,NaN,HCM-BROD-1130-C06,False,NaN,NaN,NaN,NaN,NaN,NaN
2131,ACH-003480,PT-D6v5Dz,CCLF_THYR_0001_T,CCLFTHYR0001T,THAP,Thyroid,Anaplastic Thyroid Cancer,Anaplastic Thyroid Cancer,THAP,NaN,...,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
model[model["OncotreeLineage"]=='Lung']

,ModelID,PatientID,CellLineName,StrippedCellLineName,DepmapModelType,OncotreeLineage,OncotreePrimaryDisease,OncotreeSubtype,OncotreeCode,PatientSubtypeFeatures,...,PublicComments,CCLEName,HCMIID,PediatricModelType,ModelAvailableInDbgap,ModelSubtypeFeatures,WTSIMasterCellID,SangerModelID,COSMICID,ModelIDAlias
10,ACH-000012,PT-NdspH5,HCC-827,HCC827,LUAD,Lung,Non-Small Cell Lung Cancer,Lung Adenocarcinoma,LUAD,NaN,...,NaN,HCC827_LUNG,NaN,False,Approved for public sharing - CCLE,NaN,354.0,SIDM01067,1240146.0,NaN
13,ACH-000015,PT-ffwajI,NCI-H1581,NCIH1581,LCLC,Lung,Non-Small Cell Lung Cancer,Large Cell Lung Carcinoma,LCLC,NaN,...,NaN,NCIH1581_LUNG,NaN,False,Approved for public sharing - CCLE,NaN,1237.0,SIDM00748,908471.0,ACH-000010
19,ACH-000021,PT-9p1WQv,NCI-H1693,NCIH1693,LUAD,Lung,Non-Small Cell Lung Cancer,Lung Adenocarcinoma,LUAD,NaN,...,NaN,NCIH1693_LUNG,NaN,False,Approved for public sharing - CCLE,NaN,634.0,SIDM00742,687802.0,NaN
27,ACH-000029,PT-NdspH5,HCC-827-GR5,HCC827GR5,LUAD,Lung,Non-Small Cell Lung Cancer,Lung Adenocarcinoma,LUAD,NaN,...,NaN,HCC827GR5_LUNG,NaN,False,Approved for public sharing - CCLE,NaN,NaN,NaN,NaN,NaN
28,ACH-000030,PT-nDRyc6,PC-14,PC14,LUAD,Lung,Non-Small Cell Lung Cancer,Lung Adenocarcinoma,LUAD,NaN,...,NaN,PC14_LUNG,NaN,False,Approved for public sharing - CCLE,NaN,198.0,SIDM00237,753608.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2070,ACH-003152,PT-44ykgT,ABM-T0796,ABMT0796,ZIMMEPCL,Lung,Non-Cancerous,"Immortalized Epithelial Cells, Lung",NaN,NaN,...,NaN,NaN,NaN,False,In Progress,NaN,NaN,NaN,NaN,NaN
2071,ACH-003153,PT-CL2j3Q,ABM-T0794,ABMT0794,ZIMMEPCL,Lung,Non-Cancerous,"Immortalized Epithelial Cells, Lung",NaN,NaN,...,NaN,NaN,NaN,False,In Progress,NaN,NaN,NaN,NaN,NaN
2072,ACH-003154,PT-CL2j3Q,ABM-T0795,ABMT0795,ZIMMEPCL,Lung,Non-Cancerous,"Immortalized Epithelial Cells, Lung",NaN,NaN,...,NaN,NaN,NaN,False,In Progress,NaN,NaN,NaN,NaN,NaN
2074,ACH-003156,PT-CL2j3Q,ABM-T0797,ABMT0797,ZIMMEPCL,Lung,Non-Cancerous,"Immortalized Epithelial Cells, Lung",NaN,NaN,...,NaN,NaN,NaN,False,In Progress,NaN,NaN,NaN,NaN,NaN
2075,ACH-003157,PT-QDEP9D,ABM-T0822,ABMT0822,ZIMMMPLC,Lung,Non-Cancerous,Immortalized MPLC Cells,NaN,NaN,...,NaN,NaN,NaN,False,In Progress,NaN,NaN,NaN,NaN,NaN

In [5]:
lung_id = model[model["OncotreeLineage"] == 'Lung']['ModelID']
lung_id

10      ACH-000012
13      ACH-000015
19      ACH-000021
27      ACH-000029
28      ACH-000030
           ...
2070    ACH-003152
2071    ACH-003153
2072    ACH-003154
2074    ACH-003156
2075    ACH-003157
Name: ModelID, Length: 260, dtype: str

In [6]:
expressions_data = pd.read_csv("../../../data/raw/depmap/OmicsExpressionTPMLogp1HumanProteinCodingGenes.csv")
expressions_data

,Unnamed: 0,SequencingID,ModelID,IsDefaultEntryForModel,ModelConditionID,IsDefaultEntryForMC,TSPAN6 (7105),TNMD (64102),DPM1 (8813),SCYL3 (57147),...,ATXN8 (724066),SMIM42 (117981789),NPBWR1 (2831),ACTL10 (170487),RNF228 (122319436),PANO1 (101927423),HRURF (120766137),PRRC2B (84726),F8A2 (474383),F8A1 (8263)
0,0,CDS-010xbm,ACH-001113,Yes,MC-001113-k2lR,Yes,4.956577,0.000000,7.577648,3.179411,...,0.0,0.000000,0.414727,0.077634,1.113094,0.411901,0.0,5.134808,1.214541,4.315653
1,1,CDS-02TzJp,ACH-001289,Yes,MC-001289-BpdI,Yes,4.954992,0.617243,7.334747,2.783576,...,0.0,0.000000,0.029840,0.000000,1.262156,1.026871,0.0,5.951231,0.007227,4.251060
2,2,CDS-0693hw,ACH-001339,Yes,MC-001339-5nRN,Yes,3.421952,0.000000,7.546069,2.615880,...,0.0,0.000000,0.127768,0.105594,0.413829,0.540575,0.0,4.205971,0.030894,2.783448
3,3,CDS-07Plat,ACH-001619,No,MC-001619-IR6I,No,5.196729,0.000000,6.362268,2.144996,...,0.0,0.000000,0.075396,0.932918,0.000000,0.511978,0.0,4.510747,3.223597,5.106595
4,4,CDS-08FOcu,ACH-001979,Yes,MC-001979-E3qW,Yes,4.651643,0.000000,5.946408,2.454515,...,0.0,0.000000,0.012012,0.000000,1.006470,0.729221,0.0,4.922916,0.150926,4.661556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1749,1749,CDS-zsS3zE,ACH-002669,Yes,MC-002669-Ivra,Yes,3.770702,0.000000,7.380245,1.803405,...,0.0,0.000000,0.032260,0.890296,0.185355,0.211497,0.0,5.602071,0.000000,7.062305
1750,1750,CDS-zsp0NA,ACH-001858,Yes,MC-001858-c43i,Yes,4.886794,0.000000,7.245942,2.187771,...,0.0,0.000000,1.727733,0.311457,0.179430,0.468641,0.0,5.290513,0.030359,5.632411
1751,1751,CDS-zvrgDc,ACH-001997,Yes,MC-001997-n8wz,Yes,5.721963,0.000000,8.299822,3.008067,...,0.0,0.000000,0.002292,2.102581,0.005078,0.382775,0.0,4.417502,0.008285,5.242202
1752,1752,CDS-zvw4zv,ACH-003297,Yes,MC-003297-yuio,Yes,5.614041,0.000000,9.594666,2.666827,...,0.0,0.000000,1.049101,0.000000,0.000000,1.011853,0.0,5.329231,0.000001,4.132692
1753,1753,CDS-zx92JS,ACH-000052,Yes,MC-000052-uUW6,Yes,4.478881,0.000000,6.286216,2.433657,...,0.0,0.150304,0.005927,0.939211,1.376829,1.298776,0.0,6.311400,0.464013,4.325955

In [7]:
expressions_data = expressions_data[expressions_data['IsDefaultEntryForModel'] == 'Yes']

In [8]:
expressions_data.shape

(1699, 19221)

In [9]:
lung_expression = expressions_data[expressions_data['ModelID'].isin(lung_id)]
lung_expression

,Unnamed: 0,SequencingID,ModelID,IsDefaultEntryForModel,ModelConditionID,IsDefaultEntryForMC,TSPAN6 (7105),TNMD (64102),DPM1 (8813),SCYL3 (57147),...,ATXN8 (724066),SMIM42 (117981789),NPBWR1 (2831),ACTL10 (170487),RNF228 (122319436),PANO1 (101927423),HRURF (120766137),PRRC2B (84726),F8A2 (474383),F8A1 (8263)
0,0,CDS-010xbm,ACH-001113,Yes,MC-001113-k2lR,Yes,4.956577,0.000000,7.577648,3.179411,...,0.00000,0.0,0.414727,0.077634,1.113094,0.411901,0.0,5.134808,1.214541,4.315653
9,9,CDS-0Jkjew,ACH-000327,Yes,MC-000327-k5I5,Yes,3.759710,0.000000,6.062055,1.931978,...,0.00000,0.0,0.167291,0.984557,0.030734,0.491320,0.0,3.744742,3.018606,0.254729
13,13,CDS-0PME68,ACH-000705,Yes,MC-000705-R5uy,Yes,4.643816,0.000000,6.477998,2.449667,...,0.00000,0.0,0.042438,0.259432,0.629704,0.600953,0.0,5.131668,0.258232,4.698113
16,16,CDS-0XJ78P,ACH-000528,Yes,MC-000528-BMri,Yes,4.764797,0.000000,7.203309,3.102794,...,0.00000,0.0,0.033873,0.096988,0.486864,0.530759,0.0,6.522283,0.000000,5.673958
26,26,CDS-0kkZd4,ACH-002075,Yes,MC-002075-FnYc,Yes,2.575724,0.000000,6.881897,2.784994,...,0.00000,0.0,0.053257,1.616377,2.842571,2.220135,0.0,5.739565,0.154323,6.516931
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1710,1710,CDS-ySl3GH,ACH-000666,Yes,MC-000666-6AtF,Yes,3.786199,0.000000,5.651422,2.292849,...,0.00000,0.0,0.037408,0.060065,0.400320,0.433644,0.0,6.601544,0.000000,5.124647
1714,1714,CDS-ydNWog,ACH-000872,Yes,MC-000872-Vecx,Yes,5.066873,0.000000,6.599395,3.109707,...,0.00000,0.0,0.000000,1.190368,0.000000,0.586849,0.0,5.063589,0.000000,5.703964
1722,1722,CDS-yzSR0H,ACH-000121,Yes,MC-000121-7t1B,Yes,4.332199,0.113282,6.804634,2.363227,...,0.00000,0.0,0.338120,0.784378,1.649675,1.185778,0.0,5.394603,0.000000,5.376019
1730,1730,CDS-zFnl2F,ACH-000781,Yes,MC-000781-G5rR,Yes,3.718822,0.000000,5.960069,2.118742,...,0.00000,0.0,0.005669,0.099357,0.277650,0.328002,0.0,5.705663,1.805346,4.384333
1738,1738,CDS-zYpKQj,ACH-000830,Yes,MC-000830-ZfdN,Yes,3.610157,0.000000,6.466598,2.776647,...,0.05326,0.0,0.000000,1.792231,0.875381,0.988758,0.0,7.289263,0.000000,5.712103

In [10]:
lung_expression.drop(['Unnamed: 0', 'SequencingID', 'IsDefaultEntryForModel', 'ModelConditionID', 'IsDefaultEntryForMC'], axis=1, inplace=True)

In [11]:
lung_expression

,ModelID,TSPAN6 (7105),TNMD (64102),DPM1 (8813),SCYL3 (57147),FIRRM (55732),FGR (2268),CFH (3075),FUCA2 (2519),GCLC (2729),...,ATXN8 (724066),SMIM42 (117981789),NPBWR1 (2831),ACTL10 (170487),RNF228 (122319436),PANO1 (101927423),HRURF (120766137),PRRC2B (84726),F8A2 (474383),F8A1 (8263)
0,ACH-001113,4.956577,0.000000,7.577648,3.179411,4.765742,0.037483,1.510547,3.103039,6.697482,...,0.00000,0.0,0.414727,0.077634,1.113094,0.411901,0.0,5.134808,1.214541,4.315653
9,ACH-000327,3.759710,0.000000,6.062055,1.931978,2.801039,0.008343,3.155547,6.022998,3.989239,...,0.00000,0.0,0.167291,0.984557,0.030734,0.491320,0.0,3.744742,3.018606,0.254729
13,ACH-000705,4.643816,0.000000,6.477998,2.449667,4.400859,0.038055,0.225467,2.721062,6.441122,...,0.00000,0.0,0.042438,0.259432,0.629704,0.600953,0.0,5.131668,0.258232,4.698113
16,ACH-000528,4.764797,0.000000,7.203309,3.102794,4.878814,0.015458,1.114007,6.858242,4.421156,...,0.00000,0.0,0.033873,0.096988,0.486864,0.530759,0.0,6.522283,0.000000,5.673958
26,ACH-002075,2.575724,0.000000,6.881897,2.784994,4.405652,0.824182,0.315560,3.281350,4.785237,...,0.00000,0.0,0.053257,1.616377,2.842571,2.220135,0.0,5.739565,0.154323,6.516931
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1710,ACH-000666,3.786199,0.000000,5.651422,2.292849,3.870641,0.058922,7.067908,7.460841,6.209605,...,0.00000,0.0,0.037408,0.060065,0.400320,0.433644,0.0,6.601544,0.000000,5.124647
1714,ACH-000872,5.066873,0.000000,6.599395,3.109707,3.877617,0.014222,6.936249,6.212412,4.613761,...,0.00000,0.0,0.000000,1.190368,0.000000,0.586849,0.0,5.063589,0.000000,5.703964
1722,ACH-000121,4.332199,0.113282,6.804634,2.363227,3.489569,0.065727,2.724546,6.092596,6.539840,...,0.00000,0.0,0.338120,0.784378,1.649675,1.185778,0.0,5.394603,0.000000,5.376019
1730,ACH-000781,3.718822,0.000000,5.960069,2.118742,4.046299,0.000000,6.423397,6.678016,7.790290,...,0.00000,0.0,0.005669,0.099357,0.277650,0.328002,0.0,5.705663,1.805346,4.384333
1738,ACH-000830,3.610157,0.000000,6.466598,2.776647,4.780798,0.362481,0.148231,0.922038,4.035184,...,0.05326,0.0,0.000000,1.792231,0.875381,0.988758,0.0,7.289263,0.000000,5.712103

In [12]:
lung_expression.columns = ['ModelID'] + list(lung_expression.columns[1:].str.split(" (", regex=False).str[0])

In [13]:
ppi = pd.read_csv('../../../data/lung/lung_PPI_final.csv')
ppi_genes = pd.concat([ppi['A'], ppi['B']]).unique()

In [14]:
gene_cols = lung_expression.columns[1:][lung_expression.columns[1:].isin(ppi_genes)]

In [15]:
lung_expression = lung_expression[['ModelID'] + list(gene_cols)]

In [16]:
lung_expression.shape

(212, 18343)

In [16]:
lung_expression.to_csv('../../../data/lung/Lung_expression_final.csv', index=False)

In [17]:
Crispr = pd.read_csv("../../../data/raw/depmap/CRISPRGeneEffect.csv")
Crispr

,Unnamed: 0,A1BG (1),A1CF (29974),A2M (2),A2ML1 (144568),A3GALT2 (127550),A4GALT (53947),A4GNT (51146),AAAS (8086),AACS (65985),...,ZWILCH (55055),ZWINT (11130),ZXDA (7789),ZXDB (158586),ZXDC (79364),ZYG11A (440590),ZYG11B (79699),ZYX (7791),ZZEF1 (23140),ZZZ3 (26009)
0,ACH-000015,-0.101628,0.033423,-0.084998,0.084588,-0.025752,0.014998,0.127182,-0.309637,0.087638,...,-0.329088,-0.271706,0.008982,0.066563,0.130267,0.044343,-0.182709,-0.107747,-0.135141,-0.236502
1,ACH-000045,0.071876,0.096220,0.030159,0.128536,0.010489,-0.062870,-0.067315,-0.472265,-0.116420,...,-0.149970,-0.610225,0.075264,0.227191,0.011966,-0.065919,-0.171262,0.023059,-0.206351,-0.458801
2,ACH-000094,0.100488,0.204729,0.111304,0.220877,0.022709,-0.009274,0.086337,-0.224036,0.082950,...,0.014893,-0.882753,-0.238187,0.024990,-0.128601,0.359461,-0.230729,0.231520,0.042054,-0.762764
3,ACH-000096,0.182435,-0.004316,-0.117120,0.135999,-0.169988,-0.200839,0.203096,-0.027621,0.013396,...,-0.312683,-0.410344,0.199127,0.067745,0.088566,0.175735,-0.163985,-0.366537,-0.122897,-0.104066
4,ACH-000099,-0.103127,0.075134,-0.071087,0.036089,-0.016140,-0.154740,0.024042,0.045064,-0.018520,...,-0.318896,-0.603687,0.034780,0.109159,0.150058,-0.031689,-0.422116,0.127047,-0.238114,-0.257072
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1181,ACH-002687,-0.063994,0.014906,0.119931,0.266804,0.012315,0.074110,0.006276,-0.374605,-0.065559,...,-0.262538,-0.878076,-0.022727,0.112161,0.163097,-0.017343,-0.267976,-0.140125,-0.033730,-0.738082
1182,ACH-002708,-0.008109,0.051431,0.048292,0.254607,-0.027347,-0.178628,0.223170,-0.797440,-0.155090,...,0.049700,-0.635168,-0.190640,0.138895,0.114770,-0.099998,-0.101318,-0.233697,0.040225,-0.449273
1183,ACH-002782,-0.019900,-0.034184,0.065603,0.128023,0.025150,-0.118020,0.021829,-0.324454,0.082824,...,0.005114,-0.270304,0.015133,0.045545,0.012244,-0.025254,-0.271036,-0.067795,-0.086425,-0.087778
1184,ACH-002785,-0.063686,-0.039207,0.025933,0.102223,-0.170395,0.061861,-0.044682,-0.347906,0.047099,...,0.081239,-0.157048,-0.024652,0.024075,-0.080117,-0.081808,-0.269077,-0.019338,-0.235562,-0.115628
1185,ACH-003012,-0.078337,0.057394,0.097809,0.236112,0.000839,-0.169590,0.085746,-0.535781,0.048535,...,-0.161418,-0.862785,-0.301187,0.084811,0.100871,0.192996,-0.227619,0.018162,-0.149161,-0.324425

In [18]:
Crispr.rename(columns={'Unnamed: 0':'ModelID'},inplace=True)
Crispr

,ModelID,A1BG (1),A1CF (29974),A2M (2),A2ML1 (144568),A3GALT2 (127550),A4GALT (53947),A4GNT (51146),AAAS (8086),AACS (65985),...,ZWILCH (55055),ZWINT (11130),ZXDA (7789),ZXDB (158586),ZXDC (79364),ZYG11A (440590),ZYG11B (79699),ZYX (7791),ZZEF1 (23140),ZZZ3 (26009)
0,ACH-000015,-0.101628,0.033423,-0.084998,0.084588,-0.025752,0.014998,0.127182,-0.309637,0.087638,...,-0.329088,-0.271706,0.008982,0.066563,0.130267,0.044343,-0.182709,-0.107747,-0.135141,-0.236502
1,ACH-000045,0.071876,0.096220,0.030159,0.128536,0.010489,-0.062870,-0.067315,-0.472265,-0.116420,...,-0.149970,-0.610225,0.075264,0.227191,0.011966,-0.065919,-0.171262,0.023059,-0.206351,-0.458801
2,ACH-000094,0.100488,0.204729,0.111304,0.220877,0.022709,-0.009274,0.086337,-0.224036,0.082950,...,0.014893,-0.882753,-0.238187,0.024990,-0.128601,0.359461,-0.230729,0.231520,0.042054,-0.762764
3,ACH-000096,0.182435,-0.004316,-0.117120,0.135999,-0.169988,-0.200839,0.203096,-0.027621,0.013396,...,-0.312683,-0.410344,0.199127,0.067745,0.088566,0.175735,-0.163985,-0.366537,-0.122897,-0.104066
4,ACH-000099,-0.103127,0.075134,-0.071087,0.036089,-0.016140,-0.154740,0.024042,0.045064,-0.018520,...,-0.318896,-0.603687,0.034780,0.109159,0.150058,-0.031689,-0.422116,0.127047,-0.238114,-0.257072
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1181,ACH-002687,-0.063994,0.014906,0.119931,0.266804,0.012315,0.074110,0.006276,-0.374605,-0.065559,...,-0.262538,-0.878076,-0.022727,0.112161,0.163097,-0.017343,-0.267976,-0.140125,-0.033730,-0.738082
1182,ACH-002708,-0.008109,0.051431,0.048292,0.254607,-0.027347,-0.178628,0.223170,-0.797440,-0.155090,...,0.049700,-0.635168,-0.190640,0.138895,0.114770,-0.099998,-0.101318,-0.233697,0.040225,-0.449273
1183,ACH-002782,-0.019900,-0.034184,0.065603,0.128023,0.025150,-0.118020,0.021829,-0.324454,0.082824,...,0.005114,-0.270304,0.015133,0.045545,0.012244,-0.025254,-0.271036,-0.067795,-0.086425,-0.087778
1184,ACH-002785,-0.063686,-0.039207,0.025933,0.102223,-0.170395,0.061861,-0.044682,-0.347906,0.047099,...,0.081239,-0.157048,-0.024652,0.024075,-0.080117,-0.081808,-0.269077,-0.019338,-0.235562,-0.115628
1185,ACH-003012,-0.078337,0.057394,0.097809,0.236112,0.000839,-0.169590,0.085746,-0.535781,0.048535,...,-0.161418,-0.862785,-0.301187,0.084811,0.100871,0.192996,-0.227619,0.018162,-0.149161,-0.324425

In [19]:
Crispr.columns = ['ModelID'] + list(Crispr.columns[1:].str.split(" (", regex=False).str[0])
Crispr

,ModelID,A1BG,A1CF,A2M,A2ML1,A3GALT2,A4GALT,A4GNT,AAAS,AACS,...,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1,ZZZ3
0,ACH-000015,-0.101628,0.033423,-0.084998,0.084588,-0.025752,0.014998,0.127182,-0.309637,0.087638,...,-0.329088,-0.271706,0.008982,0.066563,0.130267,0.044343,-0.182709,-0.107747,-0.135141,-0.236502
1,ACH-000045,0.071876,0.096220,0.030159,0.128536,0.010489,-0.062870,-0.067315,-0.472265,-0.116420,...,-0.149970,-0.610225,0.075264,0.227191,0.011966,-0.065919,-0.171262,0.023059,-0.206351,-0.458801
2,ACH-000094,0.100488,0.204729,0.111304,0.220877,0.022709,-0.009274,0.086337,-0.224036,0.082950,...,0.014893,-0.882753,-0.238187,0.024990,-0.128601,0.359461,-0.230729,0.231520,0.042054,-0.762764
3,ACH-000096,0.182435,-0.004316,-0.117120,0.135999,-0.169988,-0.200839,0.203096,-0.027621,0.013396,...,-0.312683,-0.410344,0.199127,0.067745,0.088566,0.175735,-0.163985,-0.366537,-0.122897,-0.104066
4,ACH-000099,-0.103127,0.075134,-0.071087,0.036089,-0.016140,-0.154740,0.024042,0.045064,-0.018520,...,-0.318896,-0.603687,0.034780,0.109159,0.150058,-0.031689,-0.422116,0.127047,-0.238114,-0.257072
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1181,ACH-002687,-0.063994,0.014906,0.119931,0.266804,0.012315,0.074110,0.006276,-0.374605,-0.065559,...,-0.262538,-0.878076,-0.022727,0.112161,0.163097,-0.017343,-0.267976,-0.140125,-0.033730,-0.738082
1182,ACH-002708,-0.008109,0.051431,0.048292,0.254607,-0.027347,-0.178628,0.223170,-0.797440,-0.155090,...,0.049700,-0.635168,-0.190640,0.138895,0.114770,-0.099998,-0.101318,-0.233697,0.040225,-0.449273
1183,ACH-002782,-0.019900,-0.034184,0.065603,0.128023,0.025150,-0.118020,0.021829,-0.324454,0.082824,...,0.005114,-0.270304,0.015133,0.045545,0.012244,-0.025254,-0.271036,-0.067795,-0.086425,-0.087778
1184,ACH-002785,-0.063686,-0.039207,0.025933,0.102223,-0.170395,0.061861,-0.044682,-0.347906,0.047099,...,0.081239,-0.157048,-0.024652,0.024075,-0.080117,-0.081808,-0.269077,-0.019338,-0.235562,-0.115628
1185,ACH-003012,-0.078337,0.057394,0.097809,0.236112,0.000839,-0.169590,0.085746,-0.535781,0.048535,...,-0.161418,-0.862785,-0.301187,0.084811,0.100871,0.192996,-0.227619,0.018162,-0.149161,-0.324425

In [20]:
Crispr_lab = Crispr.columns[1:][Crispr.columns[1:].isin(ppi_genes)]
Crispr_lab.shape

(17849,)

In [21]:
Crispr_label = Crispr[['ModelID'] + list(Crispr_lab)]
Crispr_label.shape

(1186, 17850)

In [22]:
Crispr_label = Crispr_label[Crispr_label['ModelID'].isin(lung_id)]

In [23]:
Crispr_label.to_csv("../../../data/lung/Crispr_labels_final.csv",index=False)

In [23]:
mutations = pd.read_csv("../../../data/raw/depmap/OmicsSomaticMutationsMatrixDamaging.csv")

In [24]:
mutations = mutations[(mutations['IsDefaultEntryForModel'] == 'Yes') & (mutations['IsDefaultEntryForMC'] == 'Yes')]
mutations

,Unnamed: 0,SequencingID,ModelID,ModelConditionID,IsDefaultEntryForModel,IsDefaultEntryForMC,FAM87B (400728),LINC01128 (643837),LINC02593 (100130417),SAMD11 (148398),...,CTSLP8 (1518),ANKRD19P (138649),LINC00587 (414319),LINC02907 (157927),SSX13P (326341),SSX8P (280659),SOCS5P4 (100132415),KIF4CP (347363),GLRA4 (441509),TPTE2P4 (286573)
0,0,CDS-aN8PNg,ACH-000062,MC-000062-eiDD,Yes,Yes,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,CDS-1Zvqir,ACH-001949,MC-001949-eXWn,Yes,Yes,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,CDS-qjpRtt,ACH-002059,MC-002059-DNM1,Yes,Yes,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,CDS-bOBkBi,ACH-000402,MC-000402-iC8K,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,CDS-52aoJ0,ACH-000693,MC-000693-vUEr,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3015,3015,CDS-2W4vBy,ACH-000134,MC-000134-Xj1k,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3016,3016,CDS-bkbrQT,ACH-000165,MC-000165-8cyy,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3017,3017,CDS-FCQOTY,ACH-000131,MC-000131-g6bE,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3018,3018,CDS-xxYsio,ACH-001310,MC-001310-xz7e,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3019,3019,CDS-po1c5u,ACH-001846,MC-001846-eTrK,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
mutations = mutations[mutations['ModelID'].isin(lung_id)]
mutations

,Unnamed: 0,SequencingID,ModelID,ModelConditionID,IsDefaultEntryForModel,IsDefaultEntryForMC,FAM87B (400728),LINC01128 (643837),LINC02593 (100130417),SAMD11 (148398),...,CTSLP8 (1518),ANKRD19P (138649),LINC00587 (414319),LINC02907 (157927),SSX13P (326341),SSX8P (280659),SOCS5P4 (100132415),KIF4CP (347363),GLRA4 (441509),TPTE2P4 (286573)
0,0,CDS-aN8PNg,ACH-000062,MC-000062-eiDD,Yes,Yes,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,15,CDS-4ONXNE,ACH-000669,MC-000669-MVxi,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,17,CDS-BnfCrR,ACH-000769,MC-000769-HyNe,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,23,CDS-AM22Bz,ACH-000975,MC-000975-PUD5,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,26,CDS-aP25HV,ACH-000840,MC-000840-s0Cx,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2665,2665,CDS-T3AgLS,ACH-000774,MC-000774-GTYc,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2699,2699,CDS-62liUG,ACH-000553,MC-000553-uuoP,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2737,2737,CDS-6kTcMx,ACH-000379,MC-000379-YR4E,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2827,2827,CDS-Ct0i2D,ACH-000442,MC-000442-2s22,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2901,2901,CDS-TuF6ue,ACH-002154,MC-002154-ZXYP,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:
mutations.columns = list(mutations.columns[:6]) + list(mutations.columns[6:].str.split(" (", regex=False).str[0])
mutations

,Unnamed: 0,SequencingID,ModelID,ModelConditionID,IsDefaultEntryForModel,IsDefaultEntryForMC,FAM87B,LINC01128,LINC02593,SAMD11,...,CTSLP8,ANKRD19P,LINC00587,LINC02907,SSX13P,SSX8P,SOCS5P4,KIF4CP,GLRA4,TPTE2P4
0,0,CDS-aN8PNg,ACH-000062,MC-000062-eiDD,Yes,Yes,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,15,CDS-4ONXNE,ACH-000669,MC-000669-MVxi,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,17,CDS-BnfCrR,ACH-000769,MC-000769-HyNe,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,23,CDS-AM22Bz,ACH-000975,MC-000975-PUD5,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,26,CDS-aP25HV,ACH-000840,MC-000840-s0Cx,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2665,2665,CDS-T3AgLS,ACH-000774,MC-000774-GTYc,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2699,2699,CDS-62liUG,ACH-000553,MC-000553-uuoP,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2737,2737,CDS-6kTcMx,ACH-000379,MC-000379-YR4E,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2827,2827,CDS-Ct0i2D,ACH-000442,MC-000442-2s22,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2901,2901,CDS-TuF6ue,ACH-002154,MC-002154-ZXYP,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [27]:
muta_cols = mutations.columns[6:][mutations.columns[6:].isin(ppi_genes)]
mutations= mutations[['ModelID'] + list(muta_cols)]

In [30]:
mutations.to_csv("../../../data/lung/mutations_final.csv",index = False)

In [28]:
mutations_cols = mutations.columns[1:][mutations.columns[1:].isin(ppi_genes)]
mutations = mutations[['ModelID'] + list(mutations_cols)]

In [29]:
missing = set(ppi_genes) - set(mutations.columns[1:])
missing

{'HSBP1',
 'GREM1',
 'GSTM1',
 'HLA-DQA2',
 'RPL39',
 'DGCR6',
 'NUDT4',
 'RIT1',
 'SNRPE',
 'UTS2',
 'DEFA3',
 'NRSN2',
 'SLC39A9',
 'ARF4',
 'KIAA1143',
 'HESX1',
 'SMAD1',
 'LCE3C',
 'PCP4L1',
 'RGPD1',
 'BACC1',
 'EDDM3A',
 'KRTAP1-5',
 'CDC42EP2',
 'CD300LF',
 'OR2AT4',
 'PRELID3A',
 'RPL37',
 'PRAMEF2',
 'ZC3H11C',
 'GABPB2',
 'GOLGA6B',
 'BCAS4',
 'EDN2',
 'NUTM2G',
 'CD8B',
 'HNRNPCL3',
 'KANTR',
 'ATP5MC2',
 'RAB17',
 'DLX2',
 'POTEB',
 'UQCRFS1',
 'PPP1R14A',
 'NDUFB1',
 'PIN1',
 'PCLAF',
 'RPL34',
 'MAP2K2',
 'PRODH',
 'GLIPR2',
 'FIBIN',
 'OR4F4',
 'CGB3',
 'CLDN8',
 'OR1D5',
 'BANF1',
 'PGM5',
 'CT45A10',
 'OR4F17',
 'RAN',
 'TMEM14C',
 'DAND5',
 'TOMM20',
 'NBPF26',
 'DAZ1',
 'POTEF',
 'AMY1A',
 'SPATA45',
 'CENPVL1',
 'SPATA31A6',
 'NANOS3',
 'C2orf72',
 'C5orf58',
 'LURAP1',
 'NXT1',
 'CXCL11',
 'HIGD1C',
 'TIMM23',
 'TGIF2LX',
 'PRAMEF9',
 'NFAM1',
 'LAIR2',
 'AGAP5',
 'PLEKHJ1',
 'TMSB15B',
 'C21orf140',
 'LRTM2',
 'SUPT4H1',
 'NRG4',
 'KCTD13',
 'YPEL2',
 'GAGE2A',
 'DNAJC15',
 'IFITM2',
 'TPSB2',
 'MPDU1',
 'NPIPA7',
 'PRAMEF4',
 'RHD',
 'TBC1D3K',
 'GOLGA6L1',
 'SHISA2',
 'NCF1',
 'EEF1AKMT1',
 'C8orf82',
 'ZBTB42',
 'H3C15',
 'VTI1A',
 'NIP7',
 'S100A7A',
 'PIGH',
 'UBA52',
 'NAA40',
 'WDR83OS',
 'CYP21A2',
 'GAGE12D',
 'SMIM10L2B',
 'TMEM229B',
 'C18orf32',
 'KIAA0040',
 'ARL4C',
 'RAB3B',
 'PERP',
 'SPANXD',
 'KDELR2',
 'FBXO9',
 'SPRN',
 'GTF2H4',
 'TRIM64',
 'MRGPRD',
 'THOC3',
 'GABARAP',
 'CCSAP',
 'SPIN3',
 'ZNF322',
 'CRABP1',
 'CIMIP5',
 'KRTAP19-3',
 'IGSF6',
 'DEFB130B',
 'CHRAC1',
 'UBE2L5',
 'HIGD2A',
 'MDK',
 'PMCH',
 'TAC3',
 'TP53TG3E',
 'PRR20A',
 'SYT15',
 'GRAPL',
 'VAPB',
 'CXorf51B',
 'PRAMEF7',
 'SYCE2',
 'GH1',
 'CSTA',
 'CXCL3',
 'CT45A2',
 'DCTN3',
 'NBPF15',
 'CAMK2N1',
 'ZNF213',
 'DUSP18',
 'MRFAP1L2',
 'C3AR1',
 'PGK1',
 'SDF2L1',
 'SMIM26',
 'CTAGE6',
 'OR5C1',
 'MRPS17',
 'OR13C3',
 'DEFB106B',
 'CXXC4',
 'WFDC6',
 'CATSPERZ',
 'C10orf62',
 'VTCN1',
 'OR52N4',
 'MT1H',
 'SNRPD1',
 'GSTA3',
 'TCEAL7',
 'RBMY1B',
 'RTP1',
 'SCRN1',
 'FAM156A',
 'KRTAP22-1',
 'H2AB2',
 'ETFA',
 'SPATA31A5',
 'DPCD',
 'SPRR1B',
 'SAMTOR',
 'ENKD1',
 'CRKL',
 'CCL7',
 'RPS20',
 'NANOG',
 'OR2T2',
 'ZNG1A',
 'OR3A2',
 'SLC7A6OS',
 'UPK3BL1',
 'BBIP1',
 'INSL5',
 'BGLAP',
 'DEXI',
 'CNN3',
 'UPK3BL2',
 'ITGB1BP2',
 'FOXD4L1',
 'DEFB131A',
 'DMAC1',
 'ACTR3C',
 'TNFRSF13C',
 'RPEL1',
 'DEFB109B',
 'GNG4',
 'MC4R',
 'CD59',
 'COA1',
 'TMSB4Y',
 'CFAP20',
 'CT45A8',
 'CAAP1',
 'NME3',
 'SAMD13',
 'SMIM8',
 'TEX13B',
 'PPIAL4A',
 'PDHA1',
 'PARP16',
 'PTGER2',
 'AGR3',
 'METRN',
 'NANOGP8',
 'WASHC2A',
 'OR1L1',
 'RIMBP3B',
 'SPDYE6',
 'RRAS2',
 'TIPIN',
 'TRIM73',
 'S100A13',
 'DCK',
 'TMEM167B',
 'GPR89A',
 'FCGR3A',
 'FAM174B',
 'LSM2',
 'RCAN2',
 'KRTAP13-3',
 'CFAP107',
 'FAM89B',
 'FCGR3B',
 'OR2T35',
 'NAT8',
 'KRTAP12-1',
 'CIMIP6',
 'RNF113B',
 'DDTL',
 'APOE',
 'CCDC127',
 'DNAJC30',
 'SEC22B',
 'TMEM230',
 'TRAPPC5',
 'NUDT16L1',
 'RAB40AL',
 'SPRY3',
 'DEFB103A',
 'SPP2',
 'MT-ATP6',
 'VIPR1',
 'MAPK1IP1L',
 'CLEC2L',
 'SCGB1C2',
 'CXorf51A',
 'TIMM17A',
 'MUSTN1',
 'CSH2',
 'FBXW2',
 'GSC',
 'AGRP',
 'ARF3',
 'SPANXN5',
 'CRYAA',
 'OAZ3',
 'NOMO2',
 'HSPB9',
 'SLURP1',
 'KRTAP10-3',
 'CCZ1',
 'DPH3',
 'RGPD2',
 'MTX2',
 'PYURF',
 'MALL',
 'AMY1C',
 'OR2T5',
 'NBPF14',
 'OR2T29',
 'DPH2',
 'FAM153B',
 'MOGAT1',
 'S100A14',
 'NOP10',
 'MAGEA2',
 'LIMS3',
 'USP18',
 'RSL24D1',
 'TMEM141',
 'PTGDR2',
 'SCGB2B2',
 'RPL36AL',
 'ATAT1',
 'LGALS9C',
 'BRI3',
 'ZNG1B',
 'NRGN',
 'POLR2J3',
 'SPDYE16',
 'PRAMEF25',
 'CCL13',
 'HMGN3',
 'LRRC37A2',
 'P2RY14',
 'BNIP3',
 'MRGPRX3',
 'RAB41',
 'PTRHD1',
 'OR2T27',
 'MT-CO1',
 'DESI2',
 'LAMTOR5',
 'MRPS24',
 'PGAM4',
 'NPIPA3',
 'MZT2B',
 'ATP6V0E2',
 'HIKESHI',
 'USP17L25',
 'GSTT2',
 'DTX2',
 'SF3B6',
 'ASAH2B',
 'CNTNAP3B',
 'MGST3',
 'RPS15A',
 'ACER2',
 'CDK2AP1',
 'U2AF1',
 'NUBPL',
 'MANSC4',
 'DYNLL2',
 'CLEC18A',
 'SERF1B',
 'TRIM49',
 'RPL23A',
 'FRG2',
 'COX6B1',
 'KCNE1',
 'TMEM241',
 'NBPF11',
 'UBL4A',
 'MBNL3',
 'CISD2',
 'USP17L7',
 'POLR3D',
 'NUTM2B',
 'RNF227',
 'GTF2IRD2B',
 'TSPY3',
 'GNRH1',
 'ARL4A',
 'CBS',
 'FUNDC1',
 'PSCA',
 'DNAAF19',
 'CLDN19',
 'TBC1D3C',
 'OR1D4',
 'H3-7',
 'LRRC58',
 'NUDT4B',
 'OR51B4',
 'AGAP4',
 'CEACAM16',
 'TPBGL',
 'HIGD1A',
 'BNIP1',
 'PROK1',
 'PHPT1',
 'LRRC10B',
 'TBC1D26',
 'CHRFAM7A',
 'SYCN',
 'SSR4',
 'DAZ4',
 'TUBB2A',
 'RPLP1',
 'IKBKG',
 'BPY2',
 'ZNF740',
 'KIAA2013',
 'NPFF',
 'SIAH3',
 'ANXA8',
 'PWP2',
 'FAM72D',
 'C3orf18',
 'NDUFAF8',
 'INA',
 'SIK1',
 'NCBP2',
 'OXTR',
 'TRIM43B',
 'AGAP9',
 'GSTT2B',
 'AP3S1',
 'PNRC2',
 'FSAF1',
 'FXYD2',
 'RBMY1D',
 'EOLA1',
 'AGAP6',
 'TPD52L2',
 'ASCL2',
 'HES2',
 'CFC1B',
 'ZC3H11B',
 'COA7',
 'MUC1',
 'PF4V1',
 'NSF',
 'GTF2E1',
 'SNRPD2',
 'PSMA7',
 'IGFL3',
 'TLCD3A',
 'CNIH2',
 'UBTFL1',
 'RND1',
 'MISP3',
 'LSM3',
 'CDY2A',
 'TMEM81',
 'MAFB',
 'RNF122',
 'TMEM256',
 'SAMD1',
 'POLR2J2',
 'GOLGA8G',
 'AP1S3',
 'RNASE2',
 'USP17L3',
 'TIRAP',
 'SPATA31D3',
 'DUX4',
 'FOXO3B',
 'MT-CO2',
 'TRIM64B',
 'FKBP1B',
 'GARIN5B',
 'REEP3',
 'CRP',
 'ATP5PO',
 'VKORC1',
 'UPK3B',
 'PRB3',
 'SCGB3A1',
 'GTF2IRD2',
 'HBZ',
 'CYB561D2',
 'CSDC2',
 'CDC14C',
 'OR1G1',
 'SH2D1A',
 'POTEE',
 'RNF26',
 'PCDH11Y',
 'CYB5B',
 'H2AZ1',
 'NHLRC4',
 'FOXD4L3',
 'PRAMEF10',
 'MRPS33',
 'NBPF9',
 'SPATA31C1',
 'S100P',
 'WFDC12',
 'EIF3F',
 'AQP12B',
 'PPIC',
 'CXCL10',
 'PIGY',
 'ARPP19',
 'ARL6IP1',
 'WASHC1',
 'ERICH4',
 'RAB7B',
 'NPIPB13',
 'SPRYD4',
 'LY6H',
 'PLA2G10',
 'DUSP3',
 'BRD3OS',
 'TMEM203',
 'H2AB1',
 'RBMY1E',
 'OST4',
 'ACKR4',
 'MRPL32',
 'USP17L8',
 'C4A',
 'CENPS',
 'PDHB',
 'ZNF705D',
 'NICOL1',
 'HSPA1A',
 'CAV1',
 'SPRR2E',
 'S100A5',
 'ZNF658',
 'NDUFC1',
 'NBPF19',
 'CHCHD2',
 'SPRR2B',
 'ATP6V1E2',
 'SHLD1',
 'GGACT',
 'DEFB135',
 'ZNG1C',
 'KCNE3',
 'RPL15',
 'HSPA6',
 'ACSM5',
 'NME4',
 'FZD4',
 'ANXA2R',
 'LGALS7',
 'KDELR1',
 'PIRT',
 'MRPL23',
 'GPR17',
 'CT45A3',
 'RIMBP3C',
 'DMRTC1B',
 'CMTM7',
 'LSMEM2',
 'NBPF20',
 'C1QBP',
 'PLA2G12B',
 'MCRIP2',
 'NABP1',
 'AP1S1',
 'OR2T34',
 'SVBP',
 'NTF4',
 'POTEB3',
 'SCGB1A1',
 'MT-ATP8',
 'OR3A1',
 'STRC',
 'OR2T3',
 'RSPH10B',
 'PRAMEF8',
 'SEPTIN2',
 'SDHAF4',
 'ABHD8',
 'GOLGA6A',
 'POPDC1',
 'NDUFB3',
 'GOLGA6D',
 'CMTM8',
 'FBXW10B',
 'MT1F',
 'RNASE4',
 'PPIAL4G',
 'ELOF1',
 'LRRC10',
 'MYL9',
 'SRARP',
 'ZGLP1',
 'UBE2A',
 'RDH14',
 'NDUFB4',
 'BCL7B',
 'APOBEC4',
 'LCN12',
 'POM121C',
 'GAL',
 'MIS12',
 'PDZK1',
 'GAGE12F',
 'NOTCH2NLC',
 'NPIPB6',
 'MIF4GD',
 'OAZ1',
 'PRAMEF5',
 'GOLGA8Q',
 'RGPD6',
 'RABL2A',
 'SYT15B',
 'C7orf33',
 'GMFG',
 'SPANXA2',
 'TRIM16',
 'IFNL4',
 'NBPF10',
 'ZSCAN29',
 'RPP21',
 'SPATA24',
 'RPRML',
 'FOXD4',
 'RHOXF1',
 'MRPS26',
 'SLC35B2',
 'COLEC11',
 'FOXD4L6',
 'THTPA',
 'CT55',
 'TIMM13',
 'BOLA2B',
 'TBC1D3F',
 'BIRC8',
 'TSPO2',
 'USP17L1',
 'CHD9NB',
 'EEIG1',
 'RABL2B',
 'LEPROT',
 'MAGED4',
 'MRGPRF',
 'SSU72',
 'SUV39H1',
 'KRBA2',
 'ARL17A',
 'CST9',
 'EIF4EBP1',
 'ZFY',
 'KRTAP3-2',
 'THAP12',
 'DAZ3',
 'MAGEA9B',
 'OR51G1',
 'ZNF705G',
 'GATD3',
 'ELMOD3',
 'ATOH7',
 'LCE3D',
 'TMEM216',
 'FXN',
 'H2AC20',
 'RPL27',
 'NDUFB2',
 'TMEM18',
 'RPH3AL',
 'RAP2A',
 'RPL8',
 'FAM89A',
 'SMIM11',
 'NDUFB6',
 'CT45A1',
 'ZSWIM7',
 'NRARP',
 'OR4M2',
 'EI24',
 'OR2A4',
 'NXT2',
 'CFAP97D1',
 'SPIN2B',
 'EIF4EBP2',
 'EOLA2',
 'IFI6',
 'KRTAP19-2',
 'TM2D2',
 'CT45A6',
 'BAG2',
 'FABP4',
 'GAGE12J',
 'PEA15',
 'OR10A3',
 'IL22',
 'JAGN1',
 'GOLGA8O',
 'LRRTM2',
 'CLEC18C',
 'RPS4Y1',
 'IL20',
 'RAMP3',
 'EIF3C',
 'RNASE13',
 'GAGE12G',
 'PABPC1L2B',
 'NPIPA1',
 'TMEM98',
 'VMA21',
 'NUDT14',
 'SHISA4',
 'TPSAB1',
 'SPATA31A3',
 'MAEA',
 'SPDYE1',
 'SUMO4',
 'KRTAP23-1',
 'MT1A',
 'GPR89B',
 'MRTO4',
 'POTEH',
 'RPL18',
 'INO80B',
 'CLEC4C',
 'RNF141',
 'KLRD1',
 'PPIL1',
 'ASF1B',
 'EIF3CL',
 'DPH5',
 'KRTAP2-2',
 'FAM25G',
 'SFTPC',
 'MAD2L1BP',
 'PLA2G2A',
 'LCE3A',
 'F8A3',
 'APLN',
 'SFTA2',
 'KRTAP19-1',
 'PGLYRP1',
 'CSAG2',
 'ZNF286A',
 'TMEM222',
 'SYNGR2',
 'SRGAP2C',
 'SULT1A3',
 'PDE7B',
 'RTP4',
 'NBPF6',
 'EEF1E1',
 'SLN',
 'NDUFA4L2',
 'NDUFA4',
 'DAZ2',
 'KRTAP9-6',
 'PLAAT3',
 'RPL7A',
 'NAT9',
 'OPN1MW',
 'S100G',
 'CLEC6A',
 'SRGAP2B',
 'MRPL36',
 'RAMP1',
 'SPANXC',
 'CD24',
 'MAGEA6',
 'SLBP',
 'TUBB2B',
 'GOLGA6C',
 'RPL41',
 'KRTAP9-7',
 'MYL12B',
 'CT45A9',
 'DEFB107B',
 'SNX3',
 'INO80C',
 'PPP1R1A',
 'H3Y1',
 'CALHM2',
 'CCL19',
 'LAMTOR4',
 'KRTCAP3',
 'PPP1R11',
 'CSRP1',
 'TBC1D28',
 'H1-10',
 'CLN8',
 'CD300H',
 'ARHGEF35',
 'FAM120AOS',
 'FAM86B2',
 'TCP11X2',
 'USP17L5',
 'NOMO1',
 'MTHFS',
 'MRPL3',
 'RGPD4',
 'SPDYE2B',
 'RIMBP3',
 'FBXL12',
 'DDX11',
 'MIS18A',
 'FAM72A',
 'IL36A',
 'TCAF2',
 'POLR2J',
 'USP17L18',
 'CHCHD1',
 'PSMG4',
 'IL1F10',
 'SERPINB9',
 'MBD3L2',
 'TBC1D3H',
 'TRARG1',
 'PEX39',
 'ANKRD20A1',
 'NPY4R',
 'GUK1',
 'CSNK1E',
 'S100A4',
 'PAFAH1B3',
 'ACSM2B',
 'SNRNP27',
 'ZNG1F',
 'CKMT1A',
 'TSPY10',
 'DNLZ',
 'PPP1R27',
 'LCN9',
 'OR11H1',
 'RPL36A',
 'GPR143',
 'TMEM33',
 'DYNLRB2',
 'MAGEA3',
 'TMEM70',
 'MT-ND2',
 'TMEM204',
 'MDH2',
 'RHOXF2B',
 'ASPN',
 'PLA2G2F',
 'ZFAND2B',
 'FNDC4',
 'SLX1A',
 'HNRNPCL4',
 'MZT1',
 'DEFA5',
 'CHST14',
 'SCGB1C1',
 'POU4F3',
 'GOLGA8M',
 'EXOSC5',
 'H2BC18',
 'GOLGA8N',
 'HSFX1',
 'HDDC3',
 'TTC9B',
 'TEN1',
 'SFXN5',
 'RHOXF2',
 'MANBAL',
 'SNRNP25',
 'ATP5MF',
 'BTBD6',
 'DEFB114',
 'SLC31A2',
 'RGPD8',
 'NDUFAF2',
 'SMIM10L2A',
 'USB1',
 'ANAPC15',
 'FAM86B1',
 'NUTM2D',
 'LCN8',
 'HSD17B10',
 'SDHAF2',
 'VHLL',
 'H2BC12L',
 'RPL31',
 'HSFY2',
 'FCF1',
 'IGFL1',
 'TACSTD2',
 'TNFAIP8L3',
 'SMR3A',
 'SHLD2',
 'HSD17B7',
 'S1PR3',
 'RWDD2A',
 'PBX2',
 'INSL4',
 'NME2',
 'RAB15',
 'FCGR1A',
 'RSPO1',
 'ACTR10',
 'IL17D',
 'NDUFAB1',
 'LRRC37A3',
 'DEFA1',
 'ABRACL',
 'DAP',
 'INS',
 'ASB8',
 'FAM153A',
 'WASHC2C',
 'VCY1B',
 'RAB28',
 'RAB18',
 'PRR20E',
 'TBC1D3G',
 'NDUFB7',
 'XXYLT1',
 'TRIM74',
 'FNDC8',
 'ACER3',
 'TMEM9',
 'CT45A5',
 'CCDC106',
 'CENPA',
 'SLC35D2',
 'HS6ST1',
 'RNF24',
 'TMEM174',
 'PGA3',
 'ARLN',
 'TOMM5',
 'TOMM20L',
 'KRTAP21-2',
 'GCHFR',
 'WFDC9',
 'SDR42E1',
 'CDRT15',
 'RPL28',
 'YPEL1',
 'ZNG1E',
 'SPATA9',
 'MT1X',
 'SHISA3',
 'OR4F3',
 'USP17L4',
 'NDUFA6',
 'TRIM43',
 'TSPO',
 'SPATA31A7',
 'SULT1A4',
 'SRSF9',
 'SLC13A2',
 'ACSM2A',
 'OXCT2',
 'KRTAP7-1',
 'NPIPB3',
 'MRPL18',
 'TNFAIP8L1',
 'TMEM31',
 'SMIM2',
 'SF3B5',
 'LRRC37A',
 'POTEG',
 'OR10G3',
 'APOC3',
 'TOMM40L',
 'ATP6V0E1',
 'CRYGC',
 'CIAPIN1',
 'HEPN1',
 'TVP23B',
 'GOLGA8F',
 'AMY1B',
 'TRIM49C',
 'CDY1B',
 'SCIMP',
 'PKIG',
 'SDHAF1',
 'SPINK6',
 'SSX2B',
 'NBPF3',
 'TBC1D3B',
 'HSPA1B',
 'GOLGA8J',
 'SMIM14',
 'PPIH',
 'COX7A1',
 'PPCDC',
 'OPN1LW',
 'TAS2R40',
 'GOLGA6L10',
 'TNFRSF10C',
 'RBMY1J',
 'GAGE13',
 'TAS2R20',
 'RNASE8',
 'GAGE1',
 'NANOS1',
 'MTURN',
 'CAPZA1',
 'TMEM212',
 'PGA4',
 'APOC1',
 'ENOPH1',
 'POTEJ',
 'EIF1B',
 'NUTM2A',
 'TBC1D3',
 'RAB24',
 'ARL6IP5',
 ...}

In [30]:
len(missing)

1206