In [1]:
import pandas as pd
import numpy as np

In [5]:
model = pd.read_csv("../../../data/raw/depmap/Model.csv")
model

,ModelID,PatientID,CellLineName,StrippedCellLineName,DepmapModelType,OncotreeLineage,OncotreePrimaryDisease,OncotreeSubtype,OncotreeCode,PatientSubtypeFeatures,...,PublicComments,CCLEName,HCMIID,PediatricModelType,ModelAvailableInDbgap,ModelSubtypeFeatures,WTSIMasterCellID,SangerModelID,COSMICID,ModelIDAlias
0,ACH-000001,PT-gj46wT,NIH:OVCAR-3,NIHOVCAR3,HGSOC,Ovary/Fallopian Tube,Ovarian Epithelial Tumor,High-Grade Serous Ovarian Cancer,HGSOC,NaN,...,NaN,NIHOVCAR3_OVARY,NaN,False,Approved for public sharing - CCLE,NaN,2201.0,SIDM00105,905933.0,NaN
1,ACH-000002,PT-5qa3uk,HL-60,HL60,AMLMRC,Myeloid,Acute Myeloid Leukemia,AML with Myelodysplasia-Related Changes,AMLMRC,"TP53(del), CDKN2A and NRAS mutations [PubMed=2...",...,NaN,HL60_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE,NaN,True,Approved for public sharing - CCLE,"NRAS, BCOR and CDKN2A",55.0,SIDM00829,905938.0,NaN
2,ACH-000003,PT-puKIyc,CACO2,CACO2,COAD,Bowel,Colorectal Adenocarcinoma,Colon Adenocarcinoma,COAD,NaN,...,NaN,CACO2_LARGE_INTESTINE,NaN,False,Approved for public sharing - CCLE,NaN,NaN,SIDM00891,NaN,NaN
3,ACH-000004,PT-q4K2cp,HEL,HEL,AMLNOS,Myeloid,Acute Myeloid Leukemia,"AML, NOS",AMLNOS,JAK2 and TP53 mutations,...,NaN,HEL_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE,NaN,True,Approved for public sharing - CCLE,JAK2 and TP53,783.0,SIDM00594,907053.0,NaN
4,ACH-000005,PT-q4K2cp,HEL 92.1.7,HEL9217,AML,Myeloid,Acute Myeloid Leukemia,Acute Myeloid Leukemia,AML,JAK2 and TP53 mutations,...,NaN,HEL9217_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE,NaN,True,Approved for public sharing - CCLE,NaN,NaN,SIDM00593,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2127,ACH-003473,PT-fG5tCh,CCLF_PEDS_0013_T,CCLFPEDS0013T,ERMS,Soft Tissue,Rhabdomyosarcoma,Embryonal Rhabdomyosarcoma,ERMS,NaN,...,NaN,NaN,HCM-BROD-0006-C49,True,NaN,NaN,NaN,NaN,NaN,NaN
2128,ACH-003474,PT-WxfjG3,CCLF_HNSC_0001_T,CCLFHNSC0001T,HNSC,Head and Neck,Head and Neck Squamous Cell Carcinoma,Head and Neck Squamous Cell Carcinoma,HNSC,NaN,...,NaN,NaN,HCM-BROD-1131-C06,False,NaN,NaN,NaN,NaN,NaN,NaN
2129,ACH-003475,PT-ce6oqw,CCLF_HNSC_0003_T,CCLFHNSC0003T,HNSC,Head and Neck,Head and Neck Squamous Cell Carcinoma,Head and Neck Squamous Cell Carcinoma,HNSC,NaN,...,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN
2130,ACH-003476,PT-ce6oqw,CCLF_HNSC_0002_T,CCLFHNSC0002T,ESCC,Esophagus/Stomach,Esophageal Squamous Cell Carcinoma,Esophageal Squamous Cell Carcinoma,ESCC,NaN,...,NaN,NaN,HCM-BROD-1130-C06,False,NaN,NaN,NaN,NaN,NaN,NaN
2131,ACH-003480,PT-D6v5Dz,CCLF_THYR_0001_T,CCLFTHYR0001T,THAP,Thyroid,Anaplastic Thyroid Cancer,Anaplastic Thyroid Cancer,THAP,NaN,...,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
model[model["OncotreeLineage"]=='Kidney']

,ModelID,PatientID,CellLineName,StrippedCellLineName,DepmapModelType,OncotreeLineage,OncotreePrimaryDisease,OncotreeSubtype,OncotreeCode,PatientSubtypeFeatures,...,PublicComments,CCLEName,HCMIID,PediatricModelType,ModelAvailableInDbgap,ModelSubtypeFeatures,WTSIMasterCellID,SangerModelID,COSMICID,ModelIDAlias
14,ACH-000016,PT-JnARLB,SLR 21,SLR21,CCRCC,Kidney,Renal Cell Carcinoma,Renal Clear Cell Carcinoma,CCRCC,NaN,...,NaN,SLR21_KIDNEY,NaN,False,Approved for public sharing - CCLE,NaN,NaN,NaN,NaN,NaN
44,ACH-000046,PT-zV8Sol,ACHN,ACHN,PRCC,Kidney,Renal Cell Carcinoma,Papillary Renal Cell Carcinoma,PRCC,NaN,...,NaN,ACHN_KIDNEY,NaN,False,Approved for public sharing - CCLE,NaN,371.0,SIDM00123,905950.0,NaN
47,ACH-000049,PT-qWYYgr,HEK TE,HEKTE,ZIMMEKC,Kidney,Non-Cancerous,Immortalized Embyonic Kidney Cells,NaN,NaN,...,NaN,HEKTE_KIDNEY,NaN,False,Approved for public sharing - CCLE,NaN,NaN,NaN,NaN,NaN
94,ACH-000096,PT-ABKGjf,G-401,G401,MRT,Kidney,Rhabdoid Cancer,Rhabdoid Cancer,MRT,NaN,...,NaN,G401_SOFT_TISSUE,NaN,True,Approved for public sharing - CCLE,NaN,962.0,SIDM00856,907299.0,NaN
157,ACH-000159,PT-T2g8EU,OS-RC-2,OSRC2,CCRCC,Kidney,Renal Cell Carcinoma,Renal Clear Cell Carcinoma,CCRCC,NaN,...,NaN,OSRC2_KIDNEY,NaN,False,Approved for public sharing - CCLE,NaN,1674.0,SIDM00239,909250.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1923,ACH-002528,PT-Zod1Nb,SNU-267,SNU267,CCRCC,Kidney,Renal Cell Carcinoma,Renal Clear Cell Carcinoma,CCRCC,NaN,...,NaN,SNU267_KIDNEY,NaN,False,Approved for dbGaP - HMB MDS,NaN,NaN,NaN,NaN,NaN
1928,ACH-002533,PT-wkGMuS,SNU-482,SNU482,RCC,Kidney,Renal Cell Carcinoma,Renal Cell Carcinoma,RCC,NaN,...,NaN,SNU482_KIDNEY,NaN,False,Approved for dbGaP - HMB MDS,NaN,NaN,NaN,NaN,NaN
2022,ACH-002937,PT-3GG3fe,CCLF_PEDS_0020_T,CCLFPEDS0020T,WT,Kidney,Wilms' Tumor,Wilms' Tumor,WT,NaN,...,NaN,NaN,HCM-BROD-0039-C64,True,NaN,NaN,NaN,NaN,NaN,NaN
2064,ACH-003143,PT-D0BP7N,ABM-T0616,ABMT0616,ZIMMEPCREN,Kidney,Non-Cancerous,"Immortalized Epithelial Cells, Renal",NaN,NaN,...,NaN,NaN,NaN,False,In Progress,NaN,NaN,NaN,NaN,NaN
2112,ACH-003451,PT-wwMxyt,CCLF_PEDS_0048_T,CCLFPEDS0048T,WT,Kidney,Wilms' Tumor,Wilms' Tumor,WT,NaN,...,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
kidney_id = model[model["OncotreeLineage"] == 'Kidney']['ModelID']
kidney_id

14      ACH-000016
44      ACH-000046
47      ACH-000049
94      ACH-000096
157     ACH-000159
           ...
1923    ACH-002528
1928    ACH-002533
2022    ACH-002937
2064    ACH-003143
2112    ACH-003451
Name: ModelID, Length: 74, dtype: str

In [5]:
expressions_data = pd.read_csv("../data/raw/depmap/OmicsExpressionTPMLogp1HumanProteinCodingGenes.csv")
expressions_data

,Unnamed: 0,SequencingID,ModelID,IsDefaultEntryForModel,ModelConditionID,IsDefaultEntryForMC,TSPAN6 (7105),TNMD (64102),DPM1 (8813),SCYL3 (57147),...,ATXN8 (724066),SMIM42 (117981789),NPBWR1 (2831),ACTL10 (170487),RNF228 (122319436),PANO1 (101927423),HRURF (120766137),PRRC2B (84726),F8A2 (474383),F8A1 (8263)
0,0,CDS-010xbm,ACH-001113,Yes,MC-001113-k2lR,Yes,4.956577,0.000000,7.577648,3.179411,...,0.0,0.000000,0.414727,0.077634,1.113094,0.411901,0.0,5.134808,1.214541,4.315653
1,1,CDS-02TzJp,ACH-001289,Yes,MC-001289-BpdI,Yes,4.954992,0.617243,7.334747,2.783576,...,0.0,0.000000,0.029840,0.000000,1.262156,1.026871,0.0,5.951231,0.007227,4.251060
2,2,CDS-0693hw,ACH-001339,Yes,MC-001339-5nRN,Yes,3.421952,0.000000,7.546069,2.615880,...,0.0,0.000000,0.127768,0.105594,0.413829,0.540575,0.0,4.205971,0.030894,2.783448
3,3,CDS-07Plat,ACH-001619,No,MC-001619-IR6I,No,5.196729,0.000000,6.362268,2.144996,...,0.0,0.000000,0.075396,0.932918,0.000000,0.511978,0.0,4.510747,3.223597,5.106595
4,4,CDS-08FOcu,ACH-001979,Yes,MC-001979-E3qW,Yes,4.651643,0.000000,5.946408,2.454515,...,0.0,0.000000,0.012012,0.000000,1.006470,0.729221,0.0,4.922916,0.150926,4.661556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1749,1749,CDS-zsS3zE,ACH-002669,Yes,MC-002669-Ivra,Yes,3.770702,0.000000,7.380245,1.803405,...,0.0,0.000000,0.032260,0.890296,0.185355,0.211497,0.0,5.602071,0.000000,7.062305
1750,1750,CDS-zsp0NA,ACH-001858,Yes,MC-001858-c43i,Yes,4.886794,0.000000,7.245942,2.187771,...,0.0,0.000000,1.727733,0.311457,0.179430,0.468641,0.0,5.290513,0.030359,5.632411
1751,1751,CDS-zvrgDc,ACH-001997,Yes,MC-001997-n8wz,Yes,5.721963,0.000000,8.299822,3.008067,...,0.0,0.000000,0.002292,2.102581,0.005078,0.382775,0.0,4.417502,0.008285,5.242202
1752,1752,CDS-zvw4zv,ACH-003297,Yes,MC-003297-yuio,Yes,5.614041,0.000000,9.594666,2.666827,...,0.0,0.000000,1.049101,0.000000,0.000000,1.011853,0.0,5.329231,0.000001,4.132692
1753,1753,CDS-zx92JS,ACH-000052,Yes,MC-000052-uUW6,Yes,4.478881,0.000000,6.286216,2.433657,...,0.0,0.150304,0.005927,0.939211,1.376829,1.298776,0.0,6.311400,0.464013,4.325955

In [6]:
expressions_data[expressions_data['IsDefaultEntryForModel'] == 'Yes']

,Unnamed: 0,SequencingID,ModelID,IsDefaultEntryForModel,ModelConditionID,IsDefaultEntryForMC,TSPAN6 (7105),TNMD (64102),DPM1 (8813),SCYL3 (57147),...,ATXN8 (724066),SMIM42 (117981789),NPBWR1 (2831),ACTL10 (170487),RNF228 (122319436),PANO1 (101927423),HRURF (120766137),PRRC2B (84726),F8A2 (474383),F8A1 (8263)
0,0,CDS-010xbm,ACH-001113,Yes,MC-001113-k2lR,Yes,4.956577,0.000000,7.577648,3.179411,...,0.0,0.000000,0.414727,0.077634,1.113094,0.411901,0.0,5.134808,1.214541,4.315653
1,1,CDS-02TzJp,ACH-001289,Yes,MC-001289-BpdI,Yes,4.954992,0.617243,7.334747,2.783576,...,0.0,0.000000,0.029840,0.000000,1.262156,1.026871,0.0,5.951231,0.007227,4.251060
2,2,CDS-0693hw,ACH-001339,Yes,MC-001339-5nRN,Yes,3.421952,0.000000,7.546069,2.615880,...,0.0,0.000000,0.127768,0.105594,0.413829,0.540575,0.0,4.205971,0.030894,2.783448
4,4,CDS-08FOcu,ACH-001979,Yes,MC-001979-E3qW,Yes,4.651643,0.000000,5.946408,2.454515,...,0.0,0.000000,0.012012,0.000000,1.006470,0.729221,0.0,4.922916,0.150926,4.661556
5,5,CDS-09EywZ,ACH-002438,Yes,MC-002438-Fyw5,Yes,4.336705,0.000000,6.879387,2.262824,...,0.0,0.000000,0.024008,0.984538,3.003708,0.549131,0.0,4.949465,0.000000,6.202939
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1749,1749,CDS-zsS3zE,ACH-002669,Yes,MC-002669-Ivra,Yes,3.770702,0.000000,7.380245,1.803405,...,0.0,0.000000,0.032260,0.890296,0.185355,0.211497,0.0,5.602071,0.000000,7.062305
1750,1750,CDS-zsp0NA,ACH-001858,Yes,MC-001858-c43i,Yes,4.886794,0.000000,7.245942,2.187771,...,0.0,0.000000,1.727733,0.311457,0.179430,0.468641,0.0,5.290513,0.030359,5.632411
1751,1751,CDS-zvrgDc,ACH-001997,Yes,MC-001997-n8wz,Yes,5.721963,0.000000,8.299822,3.008067,...,0.0,0.000000,0.002292,2.102581,0.005078,0.382775,0.0,4.417502,0.008285,5.242202
1752,1752,CDS-zvw4zv,ACH-003297,Yes,MC-003297-yuio,Yes,5.614041,0.000000,9.594666,2.666827,...,0.0,0.000000,1.049101,0.000000,0.000000,1.011853,0.0,5.329231,0.000001,4.132692
1753,1753,CDS-zx92JS,ACH-000052,Yes,MC-000052-uUW6,Yes,4.478881,0.000000,6.286216,2.433657,...,0.0,0.150304,0.005927,0.939211,1.376829,1.298776,0.0,6.311400,0.464013,4.325955

In [7]:
kidney_expression = expressions_data[expressions_data['ModelID'].isin(kidney_id)]
kidney_expression

,Unnamed: 0,SequencingID,ModelID,IsDefaultEntryForModel,ModelConditionID,IsDefaultEntryForMC,TSPAN6 (7105),TNMD (64102),DPM1 (8813),SCYL3 (57147),...,ATXN8 (724066),SMIM42 (117981789),NPBWR1 (2831),ACTL10 (170487),RNF228 (122319436),PANO1 (101927423),HRURF (120766137),PRRC2B (84726),F8A2 (474383),F8A1 (8263)
5,5,CDS-09EywZ,ACH-002438,Yes,MC-002438-Fyw5,Yes,4.336705,0.000000,6.879387,2.262824,...,0.0,0.000000,0.024008,0.984538,3.003708,0.549131,0.0,4.949465,0.000000,6.202939
20,20,CDS-0bEOEO,ACH-000792,Yes,MC-000792-V2Ue,Yes,3.500318,0.000000,6.572009,1.812749,...,0.0,0.000000,0.271451,0.393398,0.054122,0.251168,0.0,5.311536,0.000000,3.942646
38,38,CDS-1K6XD7,ACH-000317,Yes,MC-000317-zFR4,Yes,3.551270,0.000000,6.121229,2.008612,...,0.0,0.739040,0.179049,1.816018,0.692234,1.324684,0.0,5.852713,2.442593,4.021027
45,45,CDS-1WkIXw,ACH-000313,Yes,MC-000313-eJa9,Yes,3.815002,0.000000,5.790728,2.040068,...,0.0,0.063849,0.085998,1.043813,0.237886,0.833832,0.0,6.262553,2.734965,4.539016
81,81,CDS-2a420U,ACH-001398,Yes,MC-001398-XBHi,Yes,4.363234,0.000000,7.044121,1.939708,...,0.0,0.000000,0.495400,1.353459,0.902669,0.646028,0.0,4.534995,4.045923,4.863597
112,112,CDS-3wjudI,ACH-001200,Yes,MC-001200-sM9G,Yes,2.745519,0.000000,5.975256,2.504030,...,0.0,0.000000,0.000000,0.246098,0.057167,1.113047,0.0,6.068778,0.000000,3.876969
125,125,CDS-4U5bAO,ACH-001688,Yes,MC-001688-EWv4,Yes,4.304204,0.000000,4.627689,2.064835,...,0.0,0.435620,0.154114,1.592536,0.000000,1.200674,0.0,3.702148,0.000000,6.449380
200,200,CDS-6i5BUw,ACH-000428,Yes,MC-000428-mn7k,Yes,3.718690,0.000000,6.672397,1.969410,...,0.0,0.000000,1.069998,0.859691,0.093912,0.698136,0.0,5.345623,0.118978,4.196843
243,243,CDS-8YJJRl,ACH-000684,Yes,MC-000684-OsUg,Yes,2.841025,0.000000,6.861521,2.007027,...,0.0,0.062720,0.180875,1.258151,0.041439,0.549302,0.0,2.091297,1.721132,3.890982
248,248,CDS-8e0nyQ,ACH-000429,Yes,MC-000429-gjoP,Yes,3.656382,0.000000,6.082187,2.089559,...,0.0,0.121053,0.099411,0.272465,0.104774,0.927424,0.0,3.332303,0.847337,1.411036
252,252,CDS-8ix8rC,ACH-000234,Yes,MC-000234-uzZ9,Yes,3.573496,0.000000,6.459963,3.878735,...,0.0,0.000000,0.095789,1.559981,0.573305,0.567978,0.0,5.937196,0.047576,5.154243
256,256,CDS-8tvLDJ,ACH-003451,Yes,MC-003451-A9W6,Yes,5.740202,0.612758,6.006758,3.059833,...,0.0,0.000000,0.017147,0.184716,2.338091,1.510142,0.0,5.774816,0.000000,2.908242
293,293,CDS-AiPpwY,ACH-000600,Yes,MC-000600-vKRN,Yes,3.940082,0.000000,6.602714,2.587994,...,0.0,0.272544,0.391224,0.741829,0.320422,1.371414,0.0,5.649989,0.024952,4.487364
299,299,CDS-Apbvg2,ACH-002533,Yes,MC-002533-pOlV,Yes,5.283537,0.000000,7.109172,2.449804,...,0.0,0.000000,0.540175,0.000000,0.548843,0.060006,0.0,4.674314,4.017183,5.420354
300,300,CDS-AqUqd1,ACH-000459,Yes,MC-000459-htGX,Yes,3.111916,0.000000,6.125604,2.899203,...,0.0,0.046428,0.108326,1.206381,0.055241,0.701615,0.0,5.993985,0.000000,6.567048
332,332,CDS-Bz9YAu,ACH-000262,Yes,MC-000262-Ldf3,Yes,4.099893,0.000000,7.208420,2.018349,...,0.0,0.000000,0.060658,0.706851,0.000000,0.672557,0.0,5.573644,0.033538,4.265384
377,377,CDS-E6WUKO,ACH-001310,Yes,MC-001310-xz7e,Yes,5.110793,0.000000,6.551741,2.372139,...,0.0,0.000000,0.160474,0.554409,0.015917,0.476327,0.0,6.005948,0.016421,4.299237
379,379,CDS-EFWULO,ACH-000484,Yes,MC-000484-3iBo,Yes,2.669315,0.000000,6.542546,2.409611,...,0.0,0.000000,0.014625,1.947861,0.000000,1.242663,0.0,5.790960,0.000000,3.474306
438,438,CDS-GEyo8n,ACH-000300,Yes,MC-000300-Rw9l,Yes,4.240734,0.000000,6.403321,2.749442,...,0.0,0.000000,0.006404,0.933657,0.875000,0.634748,0.0,5.257708,0.000000,5.805922
592,592,CDS-Kyh04v,ACH-000250,Yes,MC-000250-3qw8,Yes,2.434946,0.000000,6.342743,2.670251,...,0.0,0.000000,0.238360,1.049477,0.475093,0.946762,0.0,6.111812,2.440445,4.563280
601,601,CDS-LSgxBw,ACH-001163,Yes,MC-001163-vV3z,Yes,4.567831,0.717109,6.568405,2.108548,...,0.0,0.000000,0.000000,0.052370,0.117926,0.278980,0.0,5.019751,1.941869,5.004762
624,624,CDS-MOPbK4,ACH-002937,Yes,MC-002937-gD8Q,Yes,4.049474,0.000000,5.468169,1.715849,...,0.0,0.000000,2.156982,0.787462,0.591652,0.473593,0.0,4.204720,0.000000,5.375884
626,626,CDS-MXbrpK,ACH-000049,Yes,MC-000049-k0Ty,Yes,4.541372,0.000000,6.585768,2.313510,...,0.0,0.093921,0.137837,0.379306,0.023728,0.336970,0.0,5.378630,0.000000,4.636723
801,801,CDS-RyNduV,ACH-000375,Yes,MC-000375-3NLt,Yes,3.066017,0.022658,6.134213,2.556581,...,0.0,0.000000,0.000000,0.198399,0.000000,1.387396,0.0,6.039105,2.083210,4.137389
829,829,CDS-SxzWEc,ACH-001194,Yes,MC-001194-PJUS,Yes,3.834003,0.000000,7.154575,2.629303,...,0.0,0.613815,0.094541,0.327809,0.278183,1.070066,0.0,4.047163,2.493143,4.716431
885,885,CDS-VGyWol,ACH-000649,Yes,MC-000649-Hb96,Yes,2.541101,0.000000,7.045421,2.138261,...,0.0,0.000000,0.034909,0.700837,0.032688,0.675380,0.0,5.436328,0.000000,5.355066
939,939,CDS-X6cMpP,ACH-000016,Yes,MC-000016-0Cgg,Yes,4.462530,0.000000,6.190176,2.318172,...,0.0,0.000000,0.331444,1.168360,0.169312,0.609979,0.0,5.622740,0.000000,4.043196
977,977,CDS-YpSw2C,ACH-000411,Yes,MC-000411-stVE,Yes,3.035960,0.000000,6.454929,2.434313,...,0.0,0.000000,0.098670,0.701057,0.051149,0.421399,0.0,5.022159,0.000000,5.035153
981,981,CDS-Yxd34X,ACH-000433,Yes,MC-000433-fLcb,Yes,3.939010,0.000000,6.651957,2.487566,...,0.0,0.039663,0.390630,0.412617,0.178246,0.283266,0.0,4.184883,0.000000,5.331508
990,990,CDS-ZEEQsI,ACH-002528,Yes,MC-002528-m6by,Yes,4.063839,0.000000,6.961091,2.288022,...,0.0,0.000000,0.087563,0.782536,0.053804,0.109700,0.0,5.707061,0.000038,5.808992
1071,1071,CDS-by8tR8,ACH-000533,Yes,MC-000533-fYvG,Yes,3.175275,0.000000,6.697190,2.802456,...,0.0,0.000000,0.000000,0.097415,0.177066,1.419598,0.0,5.953587,0.287275,4.189943
1074,1074,CDS-c6AfAM,ACH-000171,Yes,MC-000171-D1xj,Yes,3.191177,0.000000,6.258807,2.713379,...,0.0,0.281284,0.629548,0.295236,0.370228,0.384374,0.0,5.104639,1.364729,3.329906
1108,1108,CDS-dbJ6NK,ACH-002435,Yes,MC-002435-5hT4,Yes,4.596518,0.059017,6.063820,1.926554,...,0.0,0.000000,0.545848,0.328835,3.021460,1.124096,0.0,4.393094,3.701516,4.557612
1134,1134,CDS-eaMPk2,ACH-000201,Yes,MC-000201-rUIL,Yes,2.253672,0.000000,6.697774,3.615263,...,0.0,0.000000,0.017309,0.331820,0.059012,2.050251,0.0,5.674156,0.000000,5.220620
1190,1190,CDS-fyYnX8,ACH-000189,Yes,MC-000189-8xLJ,Yes,2.520319,0.000000,6.577403,1.751986,...,0.0,0.031972,0.662276,1.381040,0.008593,1.226095,0.0,5.447354,0.820150,4.391232
1303,1303,CDS-jmb3LU,ACH-000457,Yes,MC-000457-BEt0,Yes,4.177009,0.000000,5.870838,2.320164,...,0.0,0.066256,0.194370,1.239441,1.226952,0.664568,0.0,6.384782,0.723167,4.332450
1327,1327,CDS-kZ0HGc,ACH-000159,Yes,MC-000159-MXbI,Yes,3.989230,0.000000,7.383523,2.045974,...,0.0,0.233538,1.424175,1.528351,0.000000,0.788849,0.0,5.255063,1.150228,4.946127
1328,1328,CDS-kdNYZF,ACH-000907,Yes,MC-000907-PqcI,Yes,4.639684,0.000000,5.218677,1.917504,...,0.0,0.035893,0.088182,0.585142,0.189029,0.738037,0.0,4.818283,0.000000,5.193200
1370,1370,CDS-llvVKR,ACH-001423,Yes,MC-001423-L1R7,Yes,4.054640,0.000000,6.496641,1.321697,...,0.0,0.000000,0.000000,0.657620,0.062274,0.668082,0.0,4.553834,0.000000,4.390633
1380,1380,CDS-lzKkMG,ACH-000709,Yes,MC-000709-QsXL,Yes,3.541515,0.000000,6.326893,1.817324,...,0.0,0.000000,0.183704,0.818947,0.062746,0.238342,0.0,3.958472,2.652955,3.942571
1395,1395,CDS-mUIcpw,ACH-001210,Yes,MC-001210-DeSa,Yes,2.823582,0.142811,6.537590,2.401669,...,0.0,0.000000,0.017613,0.056726,0.042929,1.350226,0.0,6.448695,0.058840,0.059955
1398,1398,CDS-mlolyo,ACH-003143,Yes,MC-003143-qeT1,Yes,3.631745,0.000000,7.096272,2.439408,...,0.0,0.000000,0.213080,0.701354,0.393333,0.465597,0.0,5.078994,0.000000,5.642808
1418,1418,CDS-nPxDhf,ACH-000385,Yes,MC-000385-ReBQ,Yes,3.913531,0.000000,7.034348,2.532482,...,0.0,0.000000,0.065157,1.472592,0.023135,0.851498,0.0,5.682874,3.060966,2.249682
1475,1475,CDS-pO1aBc,ACH-000096,Yes,MC-000096-OrvI,Yes,5.866584,0.139489,7.064139,3.675387,...,0.0,0.000000,0.000000,0.171621,0.000000,1.273987,0.0,5.899860,0.000000,3.362296
1515,1515,CDS-qoHI3w,ACH-000495,Yes,MC-000495-g0D3,Yes,4.501102,0.000000,7.321270,2.167024,...,0.0,0.000000,0.016871,1.728090,0.158329,0.498621,0.0,5.508140,1.611475,4.928494
1546,1546,CDS-rqcIYT,ACH-000607,Yes,MC-000607-tkjL,Yes,3.270397,0.000000,5.132334,3.061273,...,0.0,0.000000,0.013987,0.169015,0.000000,1.427746,0.0,6.501856,2.073995,2.677021
1599,1599,CDS-uNIM1z,ACH-000555,Yes,MC-000555-ZjrM,Yes,3.988130,0.000000,6.612981,2.182603,...,0.0,0.042847,0.043874,0.683524,0.017785,0.694007,0.0,5.224986,0.000000,4.865028
1604,1604,CDS-uUP01E,ACH-001109,Yes,MC-001109-JbTP,Yes,2.553267,0.000000,6.090392,2.534418,...,0.0,0.000000,0.000000,1.729561,0.021987,1.305095,0.0,6.294615,1.846882,3.221418
1618,1618,CDS-uweJFN,ACH-000272,Yes,MC-000272-qQOa,Yes,3.295575,0.000000,6.199957,1.554623,...,0.0,0.036858,0.023956,1.010887,0.018007,0.381803,0.0,5.041970,2.993951,3.973014
1621,1621,CDS-v0ocx9,ACH-000513,Yes,MC-000513-jKDw,Yes,3.906919,0.000000,6.145351,2.023944,...,0.0,0.090386,0.549701,0.318076,0.008111,0.480676,0.0,5.593939,2.129408,3.664164
1655,1655,CDS-wEZCLV,ACH-001532,Yes,MC-001532-MUr8,Yes,4.122051,0.000000,6.197915,1.996595,...,0.0,0.000000,0.000000,0.042490,0.000000,1.863261,0.0,4.881082,0.001599,3.660004
1672,1672,CDS-wyN9Yu,ACH-001687,Yes,MC-001687-KHc1,Yes,2.267383,0.000000,5.303817,1.154648,...,0.0,0.000000,0.000000,0.080823,0.000000,1.436535,0.0,3.044840,0.000620,5.449449
1736,1736,CDS-zVB5Xu,ACH-000046,Yes,MC-000046-M8UB,Yes,3.802038,0.000000,6.084245,2.155208,...,0.0,0.000000,0.151959,0.519793,0.010005,0.473973,0.0,5.337586,0.000000,4.375283

In [8]:
kidney_expression

,Unnamed: 0,SequencingID,ModelID,IsDefaultEntryForModel,ModelConditionID,IsDefaultEntryForMC,TSPAN6 (7105),TNMD (64102),DPM1 (8813),SCYL3 (57147),...,ATXN8 (724066),SMIM42 (117981789),NPBWR1 (2831),ACTL10 (170487),RNF228 (122319436),PANO1 (101927423),HRURF (120766137),PRRC2B (84726),F8A2 (474383),F8A1 (8263)
5,5,CDS-09EywZ,ACH-002438,Yes,MC-002438-Fyw5,Yes,4.336705,0.000000,6.879387,2.262824,...,0.0,0.000000,0.024008,0.984538,3.003708,0.549131,0.0,4.949465,0.000000,6.202939
20,20,CDS-0bEOEO,ACH-000792,Yes,MC-000792-V2Ue,Yes,3.500318,0.000000,6.572009,1.812749,...,0.0,0.000000,0.271451,0.393398,0.054122,0.251168,0.0,5.311536,0.000000,3.942646
38,38,CDS-1K6XD7,ACH-000317,Yes,MC-000317-zFR4,Yes,3.551270,0.000000,6.121229,2.008612,...,0.0,0.739040,0.179049,1.816018,0.692234,1.324684,0.0,5.852713,2.442593,4.021027
45,45,CDS-1WkIXw,ACH-000313,Yes,MC-000313-eJa9,Yes,3.815002,0.000000,5.790728,2.040068,...,0.0,0.063849,0.085998,1.043813,0.237886,0.833832,0.0,6.262553,2.734965,4.539016
81,81,CDS-2a420U,ACH-001398,Yes,MC-001398-XBHi,Yes,4.363234,0.000000,7.044121,1.939708,...,0.0,0.000000,0.495400,1.353459,0.902669,0.646028,0.0,4.534995,4.045923,4.863597
112,112,CDS-3wjudI,ACH-001200,Yes,MC-001200-sM9G,Yes,2.745519,0.000000,5.975256,2.504030,...,0.0,0.000000,0.000000,0.246098,0.057167,1.113047,0.0,6.068778,0.000000,3.876969
125,125,CDS-4U5bAO,ACH-001688,Yes,MC-001688-EWv4,Yes,4.304204,0.000000,4.627689,2.064835,...,0.0,0.435620,0.154114,1.592536,0.000000,1.200674,0.0,3.702148,0.000000,6.449380
200,200,CDS-6i5BUw,ACH-000428,Yes,MC-000428-mn7k,Yes,3.718690,0.000000,6.672397,1.969410,...,0.0,0.000000,1.069998,0.859691,0.093912,0.698136,0.0,5.345623,0.118978,4.196843
243,243,CDS-8YJJRl,ACH-000684,Yes,MC-000684-OsUg,Yes,2.841025,0.000000,6.861521,2.007027,...,0.0,0.062720,0.180875,1.258151,0.041439,0.549302,0.0,2.091297,1.721132,3.890982
248,248,CDS-8e0nyQ,ACH-000429,Yes,MC-000429-gjoP,Yes,3.656382,0.000000,6.082187,2.089559,...,0.0,0.121053,0.099411,0.272465,0.104774,0.927424,0.0,3.332303,0.847337,1.411036
252,252,CDS-8ix8rC,ACH-000234,Yes,MC-000234-uzZ9,Yes,3.573496,0.000000,6.459963,3.878735,...,0.0,0.000000,0.095789,1.559981,0.573305,0.567978,0.0,5.937196,0.047576,5.154243
256,256,CDS-8tvLDJ,ACH-003451,Yes,MC-003451-A9W6,Yes,5.740202,0.612758,6.006758,3.059833,...,0.0,0.000000,0.017147,0.184716,2.338091,1.510142,0.0,5.774816,0.000000,2.908242
293,293,CDS-AiPpwY,ACH-000600,Yes,MC-000600-vKRN,Yes,3.940082,0.000000,6.602714,2.587994,...,0.0,0.272544,0.391224,0.741829,0.320422,1.371414,0.0,5.649989,0.024952,4.487364
299,299,CDS-Apbvg2,ACH-002533,Yes,MC-002533-pOlV,Yes,5.283537,0.000000,7.109172,2.449804,...,0.0,0.000000,0.540175,0.000000,0.548843,0.060006,0.0,4.674314,4.017183,5.420354
300,300,CDS-AqUqd1,ACH-000459,Yes,MC-000459-htGX,Yes,3.111916,0.000000,6.125604,2.899203,...,0.0,0.046428,0.108326,1.206381,0.055241,0.701615,0.0,5.993985,0.000000,6.567048
332,332,CDS-Bz9YAu,ACH-000262,Yes,MC-000262-Ldf3,Yes,4.099893,0.000000,7.208420,2.018349,...,0.0,0.000000,0.060658,0.706851,0.000000,0.672557,0.0,5.573644,0.033538,4.265384
377,377,CDS-E6WUKO,ACH-001310,Yes,MC-001310-xz7e,Yes,5.110793,0.000000,6.551741,2.372139,...,0.0,0.000000,0.160474,0.554409,0.015917,0.476327,0.0,6.005948,0.016421,4.299237
379,379,CDS-EFWULO,ACH-000484,Yes,MC-000484-3iBo,Yes,2.669315,0.000000,6.542546,2.409611,...,0.0,0.000000,0.014625,1.947861,0.000000,1.242663,0.0,5.790960,0.000000,3.474306
438,438,CDS-GEyo8n,ACH-000300,Yes,MC-000300-Rw9l,Yes,4.240734,0.000000,6.403321,2.749442,...,0.0,0.000000,0.006404,0.933657,0.875000,0.634748,0.0,5.257708,0.000000,5.805922
592,592,CDS-Kyh04v,ACH-000250,Yes,MC-000250-3qw8,Yes,2.434946,0.000000,6.342743,2.670251,...,0.0,0.000000,0.238360,1.049477,0.475093,0.946762,0.0,6.111812,2.440445,4.563280
601,601,CDS-LSgxBw,ACH-001163,Yes,MC-001163-vV3z,Yes,4.567831,0.717109,6.568405,2.108548,...,0.0,0.000000,0.000000,0.052370,0.117926,0.278980,0.0,5.019751,1.941869,5.004762
624,624,CDS-MOPbK4,ACH-002937,Yes,MC-002937-gD8Q,Yes,4.049474,0.000000,5.468169,1.715849,...,0.0,0.000000,2.156982,0.787462,0.591652,0.473593,0.0,4.204720,0.000000,5.375884
626,626,CDS-MXbrpK,ACH-000049,Yes,MC-000049-k0Ty,Yes,4.541372,0.000000,6.585768,2.313510,...,0.0,0.093921,0.137837,0.379306,0.023728,0.336970,0.0,5.378630,0.000000,4.636723
801,801,CDS-RyNduV,ACH-000375,Yes,MC-000375-3NLt,Yes,3.066017,0.022658,6.134213,2.556581,...,0.0,0.000000,0.000000,0.198399,0.000000,1.387396,0.0,6.039105,2.083210,4.137389
829,829,CDS-SxzWEc,ACH-001194,Yes,MC-001194-PJUS,Yes,3.834003,0.000000,7.154575,2.629303,...,0.0,0.613815,0.094541,0.327809,0.278183,1.070066,0.0,4.047163,2.493143,4.716431
885,885,CDS-VGyWol,ACH-000649,Yes,MC-000649-Hb96,Yes,2.541101,0.000000,7.045421,2.138261,...,0.0,0.000000,0.034909,0.700837,0.032688,0.675380,0.0,5.436328,0.000000,5.355066
939,939,CDS-X6cMpP,ACH-000016,Yes,MC-000016-0Cgg,Yes,4.462530,0.000000,6.190176,2.318172,...,0.0,0.000000,0.331444,1.168360,0.169312,0.609979,0.0,5.622740,0.000000,4.043196
977,977,CDS-YpSw2C,ACH-000411,Yes,MC-000411-stVE,Yes,3.035960,0.000000,6.454929,2.434313,...,0.0,0.000000,0.098670,0.701057,0.051149,0.421399,0.0,5.022159,0.000000,5.035153
981,981,CDS-Yxd34X,ACH-000433,Yes,MC-000433-fLcb,Yes,3.939010,0.000000,6.651957,2.487566,...,0.0,0.039663,0.390630,0.412617,0.178246,0.283266,0.0,4.184883,0.000000,5.331508
990,990,CDS-ZEEQsI,ACH-002528,Yes,MC-002528-m6by,Yes,4.063839,0.000000,6.961091,2.288022,...,0.0,0.000000,0.087563,0.782536,0.053804,0.109700,0.0,5.707061,0.000038,5.808992
1071,1071,CDS-by8tR8,ACH-000533,Yes,MC-000533-fYvG,Yes,3.175275,0.000000,6.697190,2.802456,...,0.0,0.000000,0.000000,0.097415,0.177066,1.419598,0.0,5.953587,0.287275,4.189943
1074,1074,CDS-c6AfAM,ACH-000171,Yes,MC-000171-D1xj,Yes,3.191177,0.000000,6.258807,2.713379,...,0.0,0.281284,0.629548,0.295236,0.370228,0.384374,0.0,5.104639,1.364729,3.329906
1108,1108,CDS-dbJ6NK,ACH-002435,Yes,MC-002435-5hT4,Yes,4.596518,0.059017,6.063820,1.926554,...,0.0,0.000000,0.545848,0.328835,3.021460,1.124096,0.0,4.393094,3.701516,4.557612
1134,1134,CDS-eaMPk2,ACH-000201,Yes,MC-000201-rUIL,Yes,2.253672,0.000000,6.697774,3.615263,...,0.0,0.000000,0.017309,0.331820,0.059012,2.050251,0.0,5.674156,0.000000,5.220620
1190,1190,CDS-fyYnX8,ACH-000189,Yes,MC-000189-8xLJ,Yes,2.520319,0.000000,6.577403,1.751986,...,0.0,0.031972,0.662276,1.381040,0.008593,1.226095,0.0,5.447354,0.820150,4.391232
1303,1303,CDS-jmb3LU,ACH-000457,Yes,MC-000457-BEt0,Yes,4.177009,0.000000,5.870838,2.320164,...,0.0,0.066256,0.194370,1.239441,1.226952,0.664568,0.0,6.384782,0.723167,4.332450
1327,1327,CDS-kZ0HGc,ACH-000159,Yes,MC-000159-MXbI,Yes,3.989230,0.000000,7.383523,2.045974,...,0.0,0.233538,1.424175,1.528351,0.000000,0.788849,0.0,5.255063,1.150228,4.946127
1328,1328,CDS-kdNYZF,ACH-000907,Yes,MC-000907-PqcI,Yes,4.639684,0.000000,5.218677,1.917504,...,0.0,0.035893,0.088182,0.585142,0.189029,0.738037,0.0,4.818283,0.000000,5.193200
1370,1370,CDS-llvVKR,ACH-001423,Yes,MC-001423-L1R7,Yes,4.054640,0.000000,6.496641,1.321697,...,0.0,0.000000,0.000000,0.657620,0.062274,0.668082,0.0,4.553834,0.000000,4.390633
1380,1380,CDS-lzKkMG,ACH-000709,Yes,MC-000709-QsXL,Yes,3.541515,0.000000,6.326893,1.817324,...,0.0,0.000000,0.183704,0.818947,0.062746,0.238342,0.0,3.958472,2.652955,3.942571
1395,1395,CDS-mUIcpw,ACH-001210,Yes,MC-001210-DeSa,Yes,2.823582,0.142811,6.537590,2.401669,...,0.0,0.000000,0.017613,0.056726,0.042929,1.350226,0.0,6.448695,0.058840,0.059955
1398,1398,CDS-mlolyo,ACH-003143,Yes,MC-003143-qeT1,Yes,3.631745,0.000000,7.096272,2.439408,...,0.0,0.000000,0.213080,0.701354,0.393333,0.465597,0.0,5.078994,0.000000,5.642808
1418,1418,CDS-nPxDhf,ACH-000385,Yes,MC-000385-ReBQ,Yes,3.913531,0.000000,7.034348,2.532482,...,0.0,0.000000,0.065157,1.472592,0.023135,0.851498,0.0,5.682874,3.060966,2.249682
1475,1475,CDS-pO1aBc,ACH-000096,Yes,MC-000096-OrvI,Yes,5.866584,0.139489,7.064139,3.675387,...,0.0,0.000000,0.000000,0.171621,0.000000,1.273987,0.0,5.899860,0.000000,3.362296
1515,1515,CDS-qoHI3w,ACH-000495,Yes,MC-000495-g0D3,Yes,4.501102,0.000000,7.321270,2.167024,...,0.0,0.000000,0.016871,1.728090,0.158329,0.498621,0.0,5.508140,1.611475,4.928494
1546,1546,CDS-rqcIYT,ACH-000607,Yes,MC-000607-tkjL,Yes,3.270397,0.000000,5.132334,3.061273,...,0.0,0.000000,0.013987,0.169015,0.000000,1.427746,0.0,6.501856,2.073995,2.677021
1599,1599,CDS-uNIM1z,ACH-000555,Yes,MC-000555-ZjrM,Yes,3.988130,0.000000,6.612981,2.182603,...,0.0,0.042847,0.043874,0.683524,0.017785,0.694007,0.0,5.224986,0.000000,4.865028
1604,1604,CDS-uUP01E,ACH-001109,Yes,MC-001109-JbTP,Yes,2.553267,0.000000,6.090392,2.534418,...,0.0,0.000000,0.000000,1.729561,0.021987,1.305095,0.0,6.294615,1.846882,3.221418
1618,1618,CDS-uweJFN,ACH-000272,Yes,MC-000272-qQOa,Yes,3.295575,0.000000,6.199957,1.554623,...,0.0,0.036858,0.023956,1.010887,0.018007,0.381803,0.0,5.041970,2.993951,3.973014
1621,1621,CDS-v0ocx9,ACH-000513,Yes,MC-000513-jKDw,Yes,3.906919,0.000000,6.145351,2.023944,...,0.0,0.090386,0.549701,0.318076,0.008111,0.480676,0.0,5.593939,2.129408,3.664164
1655,1655,CDS-wEZCLV,ACH-001532,Yes,MC-001532-MUr8,Yes,4.122051,0.000000,6.197915,1.996595,...,0.0,0.000000,0.000000,0.042490,0.000000,1.863261,0.0,4.881082,0.001599,3.660004
1672,1672,CDS-wyN9Yu,ACH-001687,Yes,MC-001687-KHc1,Yes,2.267383,0.000000,5.303817,1.154648,...,0.0,0.000000,0.000000,0.080823,0.000000,1.436535,0.0,3.044840,0.000620,5.449449
1736,1736,CDS-zVB5Xu,ACH-000046,Yes,MC-000046-M8UB,Yes,3.802038,0.000000,6.084245,2.155208,...,0.0,0.000000,0.151959,0.519793,0.010005,0.473973,0.0,5.337586,0.000000,4.375283

In [9]:
kidney_expression.drop(['Unnamed: 0', 'SequencingID', 'IsDefaultEntryForModel', 'ModelConditionID', 'IsDefaultEntryForMC'], axis=1, inplace=True)

In [10]:
kidney_expression

,ModelID,TSPAN6 (7105),TNMD (64102),DPM1 (8813),SCYL3 (57147),FIRRM (55732),FGR (2268),CFH (3075),FUCA2 (2519),GCLC (2729),...,ATXN8 (724066),SMIM42 (117981789),NPBWR1 (2831),ACTL10 (170487),RNF228 (122319436),PANO1 (101927423),HRURF (120766137),PRRC2B (84726),F8A2 (474383),F8A1 (8263)
5,ACH-002438,4.336705,0.000000,6.879387,2.262824,3.256491,0.000000,2.253926,6.895436,3.470992,...,0.0,0.000000,0.024008,0.984538,3.003708,0.549131,0.0,4.949465,0.000000,6.202939
20,ACH-000792,3.500318,0.000000,6.572009,1.812749,3.596935,0.093977,0.508347,6.694044,4.797376,...,0.0,0.000000,0.271451,0.393398,0.054122,0.251168,0.0,5.311536,0.000000,3.942646
38,ACH-000317,3.551270,0.000000,6.121229,2.008612,2.559269,0.079367,4.279278,5.128755,2.962580,...,0.0,0.739040,0.179049,1.816018,0.692234,1.324684,0.0,5.852713,2.442593,4.021027
45,ACH-000313,3.815002,0.000000,5.790728,2.040068,2.488430,0.214781,6.010695,5.732893,4.818355,...,0.0,0.063849,0.085998,1.043813,0.237886,0.833832,0.0,6.262553,2.734965,4.539016
81,ACH-001398,4.363234,0.000000,7.044121,1.939708,3.001002,0.000000,5.802126,6.052003,4.781118,...,0.0,0.000000,0.495400,1.353459,0.902669,0.646028,0.0,4.534995,4.045923,4.863597
112,ACH-001200,2.745519,0.000000,5.975256,2.504030,4.151461,0.000000,1.761885,6.981065,3.944868,...,0.0,0.000000,0.000000,0.246098,0.057167,1.113047,0.0,6.068778,0.000000,3.876969
125,ACH-001688,4.304204,0.000000,4.627689,2.064835,2.407018,0.006383,1.377835,4.547573,2.267518,...,0.0,0.435620,0.154114,1.592536,0.000000,1.200674,0.0,3.702148,0.000000,6.449380
200,ACH-000428,3.718690,0.000000,6.672397,1.969410,3.263720,0.080280,1.697133,6.718595,4.281602,...,0.0,0.000000,1.069998,0.859691,0.093912,0.698136,0.0,5.345623,0.118978,4.196843
243,ACH-000684,2.841025,0.000000,6.861521,2.007027,4.000171,0.010151,4.765726,7.312003,3.254236,...,0.0,0.062720,0.180875,1.258151,0.041439,0.549302,0.0,2.091297,1.721132,3.890982
248,ACH-000429,3.656382,0.000000,6.082187,2.089559,2.811607,0.084331,4.963067,4.424459,3.808920,...,0.0,0.121053,0.099411,0.272465,0.104774,0.927424,0.0,3.332303,0.847337,1.411036
252,ACH-000234,3.573496,0.000000,6.459963,3.878735,3.498698,0.028146,1.144366,6.438559,7.185847,...,0.0,0.000000,0.095789,1.559981,0.573305,0.567978,0.0,5.937196,0.047576,5.154243
256,ACH-003451,5.740202,0.612758,6.006758,3.059833,3.384908,0.032588,7.703869,5.936923,5.704828,...,0.0,0.000000,0.017147,0.184716,2.338091,1.510142,0.0,5.774816,0.000000,2.908242
293,ACH-000600,3.940082,0.000000,6.602714,2.587994,3.950730,0.000000,6.132813,7.363679,3.885047,...,0.0,0.272544,0.391224,0.741829,0.320422,1.371414,0.0,5.649989,0.024952,4.487364
299,ACH-002533,5.283537,0.000000,7.109172,2.449804,4.080607,0.000000,4.151883,6.398484,4.508853,...,0.0,0.000000,0.540175,0.000000,0.548843,0.060006,0.0,4.674314,4.017183,5.420354
300,ACH-000459,3.111916,0.000000,6.125604,2.899203,4.238626,0.067855,5.027680,6.518578,6.052394,...,0.0,0.046428,0.108326,1.206381,0.055241,0.701615,0.0,5.993985,0.000000,6.567048
332,ACH-000262,4.099893,0.000000,7.208420,2.018349,3.991916,0.000000,4.417961,6.455474,4.413222,...,0.0,0.000000,0.060658,0.706851,0.000000,0.672557,0.0,5.573644,0.033538,4.265384
377,ACH-001310,5.110793,0.000000,6.551741,2.372139,4.503603,0.091392,4.388403,6.361021,4.132017,...,0.0,0.000000,0.160474,0.554409,0.015917,0.476327,0.0,6.005948,0.016421,4.299237
379,ACH-000484,2.669315,0.000000,6.542546,2.409611,2.101754,0.212635,4.503387,5.244442,6.101007,...,0.0,0.000000,0.014625,1.947861,0.000000,1.242663,0.0,5.790960,0.000000,3.474306
438,ACH-000300,4.240734,0.000000,6.403321,2.749442,4.744344,0.035624,6.068116,6.467275,5.511436,...,0.0,0.000000,0.006404,0.933657,0.875000,0.634748,0.0,5.257708,0.000000,5.805922
592,ACH-000250,2.434946,0.000000,6.342743,2.670251,4.221382,0.188000,5.635487,6.935106,6.315050,...,0.0,0.000000,0.238360,1.049477,0.475093,0.946762,0.0,6.111812,2.440445,4.563280
601,ACH-001163,4.567831,0.717109,6.568405,2.108548,3.493045,0.000000,0.062590,4.931371,6.718019,...,0.0,0.000000,0.000000,0.052370,0.117926,0.278980,0.0,5.019751,1.941869,5.004762
624,ACH-002937,4.049474,0.000000,5.468169,1.715849,1.721871,0.000000,3.992007,5.012528,3.579011,...,0.0,0.000000,2.156982,0.787462,0.591652,0.473593,0.0,4.204720,0.000000,5.375884
626,ACH-000049,4.541372,0.000000,6.585768,2.313510,4.241695,0.036737,3.203485,6.644218,4.008012,...,0.0,0.093921,0.137837,0.379306,0.023728,0.336970,0.0,5.378630,0.000000,4.636723
801,ACH-000375,3.066017,0.022658,6.134213,2.556581,3.345856,0.000000,0.691986,3.806695,3.430285,...,0.0,0.000000,0.000000,0.198399,0.000000,1.387396,0.0,6.039105,2.083210,4.137389
829,ACH-001194,3.834003,0.000000,7.154575,2.629303,4.204704,0.047498,8.141841,6.075411,6.136677,...,0.0,0.613815,0.094541,0.327809,0.278183,1.070066,0.0,4.047163,2.493143,4.716431
885,ACH-000649,2.541101,0.000000,7.045421,2.138261,4.501223,0.000000,3.454355,6.997281,4.565597,...,0.0,0.000000,0.034909,0.700837,0.032688,0.675380,0.0,5.436328,0.000000,5.355066
939,ACH-000016,4.462530,0.000000,6.190176,2.318172,2.366722,0.000000,7.391630,6.127134,6.312458,...,0.0,0.000000,0.331444,1.168360,0.169312,0.609979,0.0,5.622740,0.000000,4.043196
977,ACH-000411,3.035960,0.000000,6.454929,2.434313,4.310231,0.000000,1.818912,6.588511,4.972454,...,0.0,0.000000,0.098670,0.701057,0.051149,0.421399,0.0,5.022159,0.000000,5.035153
981,ACH-000433,3.939010,0.000000,6.651957,2.487566,3.264751,0.000000,4.360554,6.050957,4.702525,...,0.0,0.039663,0.390630,0.412617,0.178246,0.283266,0.0,4.184883,0.000000,5.331508
990,ACH-002528,4.063839,0.000000,6.961091,2.288022,3.659205,0.000000,7.273460,6.552692,3.575772,...,0.0,0.000000,0.087563,0.782536,0.053804,0.109700,0.0,5.707061,0.000038,5.808992
1071,ACH-000533,3.175275,0.000000,6.697190,2.802456,3.420612,0.014715,0.138218,0.956856,3.498213,...,0.0,0.000000,0.000000,0.097415,0.177066,1.419598,0.0,5.953587,0.287275,4.189943
1074,ACH-000171,3.191177,0.000000,6.258807,2.713379,3.540337,0.038095,3.597412,6.505664,5.553812,...,0.0,0.281284,0.629548,0.295236,0.370228,0.384374,0.0,5.104639,1.364729,3.329906
1108,ACH-002435,4.596518,0.059017,6.063820,1.926554,2.792683,0.000000,4.200599,5.926379,3.330600,...,0.0,0.000000,0.545848,0.328835,3.021460,1.124096,0.0,4.393094,3.701516,4.557612
1134,ACH-000201,2.253672,0.000000,6.697774,3.615263,3.964814,0.041306,4.390282,6.809620,3.259505,...,0.0,0.000000,0.017309,0.331820,0.059012,2.050251,0.0,5.674156,0.000000,5.220620
1190,ACH-000189,2.520319,0.000000,6.577403,1.751986,2.670777,0.045931,1.059909,5.391799,3.401710,...,0.0,0.031972,0.662276,1.381040,0.008593,1.226095,0.0,5.447354,0.820150,4.391232
1303,ACH-000457,4.177009,0.000000,5.870838,2.320164,1.860438,0.000000,3.994715,6.174496,4.687296,...,0.0,0.066256,0.194370,1.239441,1.226952,0.664568,0.0,6.384782,0.723167,4.332450
1327,ACH-000159,3.989230,0.000000,7.383523,2.045974,3.583050,0.084943,5.451969,5.891820,3.414689,...,0.0,0.233538,1.424175,1.528351,0.000000,0.788849,0.0,5.255063,1.150228,4.946127
1328,ACH-000907,4.639684,0.000000,5.218677,1.917504,2.662178,0.000000,6.516077,6.600649,3.582580,...,0.0,0.035893,0.088182,0.585142,0.189029,0.738037,0.0,4.818283,0.000000,5.193200
1370,ACH-001423,4.054640,0.000000,6.496641,1.321697,2.407293,0.000000,4.529396,5.287927,3.588649,...,0.0,0.000000,0.000000,0.657620,0.062274,0.668082,0.0,4.553834,0.000000,4.390633
1380,ACH-000709,3.541515,0.000000,6.326893,1.817324,3.249456,0.030405,5.397334,6.330707,3.919102,...,0.0,0.000000,0.183704,0.818947,0.062746,0.238342,0.0,3.958472,2.652955,3.942571
1395,ACH-001210,2.823582,0.142811,6.537590,2.401669,3.732801,0.000000,0.157224,7.071344,3.551799,...,0.0,0.000000,0.017613,0.056726,0.042929,1.350226,0.0,6.448695,0.058840,0.059955
1398,ACH-003143,3.631745,0.000000,7.096272,2.439408,4.609134,0.124742,4.063555,6.553466,4.034154,...,0.0,0.000000,0.213080,0.701354,0.393333,0.465597,0.0,5.078994,0.000000,5.642808
1418,ACH-000385,3.913531,0.000000,7.034348,2.532482,4.246172,0.025451,6.599856,6.808655,5.895988,...,0.0,0.000000,0.065157,1.472592,0.023135,0.851498,0.0,5.682874,3.060966,2.249682
1475,ACH-000096,5.866584,0.139489,7.064139,3.675387,4.852289,0.000000,1.110129,5.796260,4.495088,...,0.0,0.000000,0.000000,0.171621,0.000000,1.273987,0.0,5.899860,0.000000,3.362296
1515,ACH-000495,4.501102,0.000000,7.321270,2.167024,3.523537,0.103276,5.749711,6.161293,3.992750,...,0.0,0.000000,0.016871,1.728090,0.158329,0.498621,0.0,5.508140,1.611475,4.928494
1546,ACH-000607,3.270397,0.000000,5.132334,3.061273,3.836914,0.056952,7.527946,5.372816,3.855003,...,0.0,0.000000,0.013987,0.169015,0.000000,1.427746,0.0,6.501856,2.073995,2.677021
1599,ACH-000555,3.988130,0.000000,6.612981,2.182603,3.399166,0.012235,6.071098,6.075595,5.605322,...,0.0,0.042847,0.043874,0.683524,0.017785,0.694007,0.0,5.224986,0.000000,4.865028
1604,ACH-001109,2.553267,0.000000,6.090392,2.534418,3.809219,0.000000,4.032551,6.588529,3.955341,...,0.0,0.000000,0.000000,1.729561,0.021987,1.305095,0.0,6.294615,1.846882,3.221418
1618,ACH-000272,3.295575,0.000000,6.199957,1.554623,3.600781,0.000000,0.731281,6.911008,3.868242,...,0.0,0.036858,0.023956,1.010887,0.018007,0.381803,0.0,5.041970,2.993951,3.973014
1621,ACH-000513,3.906919,0.000000,6.145351,2.023944,3.361970,0.048953,6.035745,4.242267,3.887545,...,0.0,0.090386,0.549701,0.318076,0.008111,0.480676,0.0,5.593939,2.129408,3.664164
1655,ACH-001532,4.122051,0.000000,6.197915,1.996595,2.276565,0.022155,0.000000,5.879787,4.215321,...,0.0,0.000000,0.000000,0.042490,0.000000,1.863261,0.0,4.881082,0.001599,3.660004
1672,ACH-001687,2.267383,0.000000,5.303817,1.154648,0.851320,0.014641,2.172036,4.969316,2.744084,...,0.0,0.000000,0.000000,0.080823,0.000000,1.436535,0.0,3.044840,0.000620,5.449449
1736,ACH-000046,3.802038,0.000000,6.084245,2.155208,3.685794,0.015700,1.011288,6.905977,4.790511,...,0.0,0.000000,0.151959,0.519793,0.010005,0.473973,0.0,5.337586,0.000000,4.375283

In [11]:
kidney_expression.columns = ['ModelID'] + list(kidney_expression.columns[1:].str.split(" (", regex=False).str[0])

In [12]:
kidney_expression

,ModelID,TSPAN6,TNMD,DPM1,SCYL3,FIRRM,FGR,CFH,FUCA2,GCLC,...,ATXN8,SMIM42,NPBWR1,ACTL10,RNF228,PANO1,HRURF,PRRC2B,F8A2,F8A1
5,ACH-002438,4.336705,0.000000,6.879387,2.262824,3.256491,0.000000,2.253926,6.895436,3.470992,...,0.0,0.000000,0.024008,0.984538,3.003708,0.549131,0.0,4.949465,0.000000,6.202939
20,ACH-000792,3.500318,0.000000,6.572009,1.812749,3.596935,0.093977,0.508347,6.694044,4.797376,...,0.0,0.000000,0.271451,0.393398,0.054122,0.251168,0.0,5.311536,0.000000,3.942646
38,ACH-000317,3.551270,0.000000,6.121229,2.008612,2.559269,0.079367,4.279278,5.128755,2.962580,...,0.0,0.739040,0.179049,1.816018,0.692234,1.324684,0.0,5.852713,2.442593,4.021027
45,ACH-000313,3.815002,0.000000,5.790728,2.040068,2.488430,0.214781,6.010695,5.732893,4.818355,...,0.0,0.063849,0.085998,1.043813,0.237886,0.833832,0.0,6.262553,2.734965,4.539016
81,ACH-001398,4.363234,0.000000,7.044121,1.939708,3.001002,0.000000,5.802126,6.052003,4.781118,...,0.0,0.000000,0.495400,1.353459,0.902669,0.646028,0.0,4.534995,4.045923,4.863597
112,ACH-001200,2.745519,0.000000,5.975256,2.504030,4.151461,0.000000,1.761885,6.981065,3.944868,...,0.0,0.000000,0.000000,0.246098,0.057167,1.113047,0.0,6.068778,0.000000,3.876969
125,ACH-001688,4.304204,0.000000,4.627689,2.064835,2.407018,0.006383,1.377835,4.547573,2.267518,...,0.0,0.435620,0.154114,1.592536,0.000000,1.200674,0.0,3.702148,0.000000,6.449380
200,ACH-000428,3.718690,0.000000,6.672397,1.969410,3.263720,0.080280,1.697133,6.718595,4.281602,...,0.0,0.000000,1.069998,0.859691,0.093912,0.698136,0.0,5.345623,0.118978,4.196843
243,ACH-000684,2.841025,0.000000,6.861521,2.007027,4.000171,0.010151,4.765726,7.312003,3.254236,...,0.0,0.062720,0.180875,1.258151,0.041439,0.549302,0.0,2.091297,1.721132,3.890982
248,ACH-000429,3.656382,0.000000,6.082187,2.089559,2.811607,0.084331,4.963067,4.424459,3.808920,...,0.0,0.121053,0.099411,0.272465,0.104774,0.927424,0.0,3.332303,0.847337,1.411036
252,ACH-000234,3.573496,0.000000,6.459963,3.878735,3.498698,0.028146,1.144366,6.438559,7.185847,...,0.0,0.000000,0.095789,1.559981,0.573305,0.567978,0.0,5.937196,0.047576,5.154243
256,ACH-003451,5.740202,0.612758,6.006758,3.059833,3.384908,0.032588,7.703869,5.936923,5.704828,...,0.0,0.000000,0.017147,0.184716,2.338091,1.510142,0.0,5.774816,0.000000,2.908242
293,ACH-000600,3.940082,0.000000,6.602714,2.587994,3.950730,0.000000,6.132813,7.363679,3.885047,...,0.0,0.272544,0.391224,0.741829,0.320422,1.371414,0.0,5.649989,0.024952,4.487364
299,ACH-002533,5.283537,0.000000,7.109172,2.449804,4.080607,0.000000,4.151883,6.398484,4.508853,...,0.0,0.000000,0.540175,0.000000,0.548843,0.060006,0.0,4.674314,4.017183,5.420354
300,ACH-000459,3.111916,0.000000,6.125604,2.899203,4.238626,0.067855,5.027680,6.518578,6.052394,...,0.0,0.046428,0.108326,1.206381,0.055241,0.701615,0.0,5.993985,0.000000,6.567048
332,ACH-000262,4.099893,0.000000,7.208420,2.018349,3.991916,0.000000,4.417961,6.455474,4.413222,...,0.0,0.000000,0.060658,0.706851,0.000000,0.672557,0.0,5.573644,0.033538,4.265384
377,ACH-001310,5.110793,0.000000,6.551741,2.372139,4.503603,0.091392,4.388403,6.361021,4.132017,...,0.0,0.000000,0.160474,0.554409,0.015917,0.476327,0.0,6.005948,0.016421,4.299237
379,ACH-000484,2.669315,0.000000,6.542546,2.409611,2.101754,0.212635,4.503387,5.244442,6.101007,...,0.0,0.000000,0.014625,1.947861,0.000000,1.242663,0.0,5.790960,0.000000,3.474306
438,ACH-000300,4.240734,0.000000,6.403321,2.749442,4.744344,0.035624,6.068116,6.467275,5.511436,...,0.0,0.000000,0.006404,0.933657,0.875000,0.634748,0.0,5.257708,0.000000,5.805922
592,ACH-000250,2.434946,0.000000,6.342743,2.670251,4.221382,0.188000,5.635487,6.935106,6.315050,...,0.0,0.000000,0.238360,1.049477,0.475093,0.946762,0.0,6.111812,2.440445,4.563280
601,ACH-001163,4.567831,0.717109,6.568405,2.108548,3.493045,0.000000,0.062590,4.931371,6.718019,...,0.0,0.000000,0.000000,0.052370,0.117926,0.278980,0.0,5.019751,1.941869,5.004762
624,ACH-002937,4.049474,0.000000,5.468169,1.715849,1.721871,0.000000,3.992007,5.012528,3.579011,...,0.0,0.000000,2.156982,0.787462,0.591652,0.473593,0.0,4.204720,0.000000,5.375884
626,ACH-000049,4.541372,0.000000,6.585768,2.313510,4.241695,0.036737,3.203485,6.644218,4.008012,...,0.0,0.093921,0.137837,0.379306,0.023728,0.336970,0.0,5.378630,0.000000,4.636723
801,ACH-000375,3.066017,0.022658,6.134213,2.556581,3.345856,0.000000,0.691986,3.806695,3.430285,...,0.0,0.000000,0.000000,0.198399,0.000000,1.387396,0.0,6.039105,2.083210,4.137389
829,ACH-001194,3.834003,0.000000,7.154575,2.629303,4.204704,0.047498,8.141841,6.075411,6.136677,...,0.0,0.613815,0.094541,0.327809,0.278183,1.070066,0.0,4.047163,2.493143,4.716431
885,ACH-000649,2.541101,0.000000,7.045421,2.138261,4.501223,0.000000,3.454355,6.997281,4.565597,...,0.0,0.000000,0.034909,0.700837,0.032688,0.675380,0.0,5.436328,0.000000,5.355066
939,ACH-000016,4.462530,0.000000,6.190176,2.318172,2.366722,0.000000,7.391630,6.127134,6.312458,...,0.0,0.000000,0.331444,1.168360,0.169312,0.609979,0.0,5.622740,0.000000,4.043196
977,ACH-000411,3.035960,0.000000,6.454929,2.434313,4.310231,0.000000,1.818912,6.588511,4.972454,...,0.0,0.000000,0.098670,0.701057,0.051149,0.421399,0.0,5.022159,0.000000,5.035153
981,ACH-000433,3.939010,0.000000,6.651957,2.487566,3.264751,0.000000,4.360554,6.050957,4.702525,...,0.0,0.039663,0.390630,0.412617,0.178246,0.283266,0.0,4.184883,0.000000,5.331508
990,ACH-002528,4.063839,0.000000,6.961091,2.288022,3.659205,0.000000,7.273460,6.552692,3.575772,...,0.0,0.000000,0.087563,0.782536,0.053804,0.109700,0.0,5.707061,0.000038,5.808992
1071,ACH-000533,3.175275,0.000000,6.697190,2.802456,3.420612,0.014715,0.138218,0.956856,3.498213,...,0.0,0.000000,0.000000,0.097415,0.177066,1.419598,0.0,5.953587,0.287275,4.189943
1074,ACH-000171,3.191177,0.000000,6.258807,2.713379,3.540337,0.038095,3.597412,6.505664,5.553812,...,0.0,0.281284,0.629548,0.295236,0.370228,0.384374,0.0,5.104639,1.364729,3.329906
1108,ACH-002435,4.596518,0.059017,6.063820,1.926554,2.792683,0.000000,4.200599,5.926379,3.330600,...,0.0,0.000000,0.545848,0.328835,3.021460,1.124096,0.0,4.393094,3.701516,4.557612
1134,ACH-000201,2.253672,0.000000,6.697774,3.615263,3.964814,0.041306,4.390282,6.809620,3.259505,...,0.0,0.000000,0.017309,0.331820,0.059012,2.050251,0.0,5.674156,0.000000,5.220620
1190,ACH-000189,2.520319,0.000000,6.577403,1.751986,2.670777,0.045931,1.059909,5.391799,3.401710,...,0.0,0.031972,0.662276,1.381040,0.008593,1.226095,0.0,5.447354,0.820150,4.391232
1303,ACH-000457,4.177009,0.000000,5.870838,2.320164,1.860438,0.000000,3.994715,6.174496,4.687296,...,0.0,0.066256,0.194370,1.239441,1.226952,0.664568,0.0,6.384782,0.723167,4.332450
1327,ACH-000159,3.989230,0.000000,7.383523,2.045974,3.583050,0.084943,5.451969,5.891820,3.414689,...,0.0,0.233538,1.424175,1.528351,0.000000,0.788849,0.0,5.255063,1.150228,4.946127
1328,ACH-000907,4.639684,0.000000,5.218677,1.917504,2.662178,0.000000,6.516077,6.600649,3.582580,...,0.0,0.035893,0.088182,0.585142,0.189029,0.738037,0.0,4.818283,0.000000,5.193200
1370,ACH-001423,4.054640,0.000000,6.496641,1.321697,2.407293,0.000000,4.529396,5.287927,3.588649,...,0.0,0.000000,0.000000,0.657620,0.062274,0.668082,0.0,4.553834,0.000000,4.390633
1380,ACH-000709,3.541515,0.000000,6.326893,1.817324,3.249456,0.030405,5.397334,6.330707,3.919102,...,0.0,0.000000,0.183704,0.818947,0.062746,0.238342,0.0,3.958472,2.652955,3.942571
1395,ACH-001210,2.823582,0.142811,6.537590,2.401669,3.732801,0.000000,0.157224,7.071344,3.551799,...,0.0,0.000000,0.017613,0.056726,0.042929,1.350226,0.0,6.448695,0.058840,0.059955
1398,ACH-003143,3.631745,0.000000,7.096272,2.439408,4.609134,0.124742,4.063555,6.553466,4.034154,...,0.0,0.000000,0.213080,0.701354,0.393333,0.465597,0.0,5.078994,0.000000,5.642808
1418,ACH-000385,3.913531,0.000000,7.034348,2.532482,4.246172,0.025451,6.599856,6.808655,5.895988,...,0.0,0.000000,0.065157,1.472592,0.023135,0.851498,0.0,5.682874,3.060966,2.249682
1475,ACH-000096,5.866584,0.139489,7.064139,3.675387,4.852289,0.000000,1.110129,5.796260,4.495088,...,0.0,0.000000,0.000000,0.171621,0.000000,1.273987,0.0,5.899860,0.000000,3.362296
1515,ACH-000495,4.501102,0.000000,7.321270,2.167024,3.523537,0.103276,5.749711,6.161293,3.992750,...,0.0,0.000000,0.016871,1.728090,0.158329,0.498621,0.0,5.508140,1.611475,4.928494
1546,ACH-000607,3.270397,0.000000,5.132334,3.061273,3.836914,0.056952,7.527946,5.372816,3.855003,...,0.0,0.000000,0.013987,0.169015,0.000000,1.427746,0.0,6.501856,2.073995,2.677021
1599,ACH-000555,3.988130,0.000000,6.612981,2.182603,3.399166,0.012235,6.071098,6.075595,5.605322,...,0.0,0.042847,0.043874,0.683524,0.017785,0.694007,0.0,5.224986,0.000000,4.865028
1604,ACH-001109,2.553267,0.000000,6.090392,2.534418,3.809219,0.000000,4.032551,6.588529,3.955341,...,0.0,0.000000,0.000000,1.729561,0.021987,1.305095,0.0,6.294615,1.846882,3.221418
1618,ACH-000272,3.295575,0.000000,6.199957,1.554623,3.600781,0.000000,0.731281,6.911008,3.868242,...,0.0,0.036858,0.023956,1.010887,0.018007,0.381803,0.0,5.041970,2.993951,3.973014
1621,ACH-000513,3.906919,0.000000,6.145351,2.023944,3.361970,0.048953,6.035745,4.242267,3.887545,...,0.0,0.090386,0.549701,0.318076,0.008111,0.480676,0.0,5.593939,2.129408,3.664164
1655,ACH-001532,4.122051,0.000000,6.197915,1.996595,2.276565,0.022155,0.000000,5.879787,4.215321,...,0.0,0.000000,0.000000,0.042490,0.000000,1.863261,0.0,4.881082,0.001599,3.660004
1672,ACH-001687,2.267383,0.000000,5.303817,1.154648,0.851320,0.014641,2.172036,4.969316,2.744084,...,0.0,0.000000,0.000000,0.080823,0.000000,1.436535,0.0,3.044840,0.000620,5.449449
1736,ACH-000046,3.802038,0.000000,6.084245,2.155208,3.685794,0.015700,1.011288,6.905977,4.790511,...,0.0,0.000000,0.151959,0.519793,0.010005,0.473973,0.0,5.337586,0.000000,4.375283

In [13]:
ppi = pd.read_csv('../data/processed/kidney_PPI_final.csv')
ppi_genes = pd.concat([ppi['A'], ppi['B']]).unique()

In [14]:
gene_cols = kidney_expression.columns[1:][kidney_expression.columns[1:].isin(ppi_genes)]

In [15]:
kidney_expression = kidney_expression[['ModelID'] + list(gene_cols)]

In [16]:
kidney_expression.shape

(53, 18360)

In [17]:
kidney_expression.to_csv('../data/processed/Kidney_expression_final.csv', index=False)

In [18]:
kidney_expression

,ModelID,TSPAN6,TNMD,DPM1,SCYL3,FIRRM,FGR,CFH,FUCA2,GCLC,...,CCDC39,UPK3BL2,ARHGAP11B,ASDURF,DERPC,NOTCH2NLC,H3C2,NPBWR1,ACTL10,PRRC2B
5,ACH-002438,4.336705,0.000000,6.879387,2.262824,3.256491,0.000000,2.253926,6.895436,3.470992,...,0.456676,1.819562,1.553459,2.227735,4.147062,3.458790,0.255362,0.024008,0.984538,4.949465
20,ACH-000792,3.500318,0.000000,6.572009,1.812749,3.596935,0.093977,0.508347,6.694044,4.797376,...,2.089447,1.716346,3.057705,0.701833,2.096609,4.620088,0.659900,0.271451,0.393398,5.311536
38,ACH-000317,3.551270,0.000000,6.121229,2.008612,2.559269,0.079367,4.279278,5.128755,2.962580,...,2.262349,3.567679,2.142609,0.966736,4.076764,3.735825,0.193359,0.179049,1.816018,5.852713
45,ACH-000313,3.815002,0.000000,5.790728,2.040068,2.488430,0.214781,6.010695,5.732893,4.818355,...,2.574240,3.410553,2.816823,1.277265,3.605435,4.499100,0.512084,0.085998,1.043813,6.262553
81,ACH-001398,4.363234,0.000000,7.044121,1.939708,3.001002,0.000000,5.802126,6.052003,4.781118,...,0.553027,3.737059,1.613800,2.627845,3.619706,4.617275,0.563187,0.495400,1.353459,4.534995
112,ACH-001200,2.745519,0.000000,5.975256,2.504030,4.151461,0.000000,1.761885,6.981065,3.944868,...,0.788148,4.487776,2.436034,3.444336,2.297133,3.649466,0.336071,0.000000,0.246098,6.068778
125,ACH-001688,4.304204,0.000000,4.627689,2.064835,2.407018,0.006383,1.377835,4.547573,2.267518,...,0.162523,5.947512,1.446981,0.126736,3.240294,3.480007,0.507673,0.154114,1.592536,3.702148
200,ACH-000428,3.718690,0.000000,6.672397,1.969410,3.263720,0.080280,1.697133,6.718595,4.281602,...,1.354746,2.313019,1.972579,2.292063,4.185367,2.900196,0.946023,1.069998,0.859691,5.345623
243,ACH-000684,2.841025,0.000000,6.861521,2.007027,4.000171,0.010151,4.765726,7.312003,3.254236,...,0.689704,2.508353,1.381533,0.993621,3.410581,4.150227,0.341549,0.180875,1.258151,2.091297
248,ACH-000429,3.656382,0.000000,6.082187,2.089559,2.811607,0.084331,4.963067,4.424459,3.808920,...,1.372239,3.478972,3.165299,2.005874,2.159413,2.163183,0.761976,0.099411,0.272465,3.332303
252,ACH-000234,3.573496,0.000000,6.459963,3.878735,3.498698,0.028146,1.144366,6.438559,7.185847,...,1.868742,3.580170,1.782081,0.847151,3.167504,3.210007,0.680033,0.095789,1.559981,5.937196
256,ACH-003451,5.740202,0.612758,6.006758,3.059833,3.384908,0.032588,7.703869,5.936923,5.704828,...,1.538181,1.218019,1.623623,2.372401,3.168456,3.108257,1.304201,0.017147,0.184716,5.774816
293,ACH-000600,3.940082,0.000000,6.602714,2.587994,3.950730,0.000000,6.132813,7.363679,3.885047,...,2.045013,2.907769,1.699565,2.167984,3.247865,2.979310,0.420340,0.391224,0.741829,5.649989
299,ACH-002533,5.283537,0.000000,7.109172,2.449804,4.080607,0.000000,4.151883,6.398484,4.508853,...,0.530201,1.350237,1.208586,3.286838,5.074921,5.036424,0.122518,0.540175,0.000000,4.674314
300,ACH-000459,3.111916,0.000000,6.125604,2.899203,4.238626,0.067855,5.027680,6.518578,6.052394,...,1.117462,3.007147,2.732345,1.827433,3.518107,4.219974,0.356978,0.108326,1.206381,5.993985
332,ACH-000262,4.099893,0.000000,7.208420,2.018349,3.991916,0.000000,4.417961,6.455474,4.413222,...,1.881845,2.839024,2.503565,1.924370,2.093969,1.939640,0.306006,0.060658,0.706851,5.573644
377,ACH-001310,5.110793,0.000000,6.551741,2.372139,4.503603,0.091392,4.388403,6.361021,4.132017,...,2.310666,1.742088,2.527028,2.552982,4.933115,3.764006,0.734168,0.160474,0.554409,6.005948
379,ACH-000484,2.669315,0.000000,6.542546,2.409611,2.101754,0.212635,4.503387,5.244442,6.101007,...,1.918562,3.391722,3.645517,1.714540,3.686601,2.803215,1.239618,0.014625,1.947861,5.790960
438,ACH-000300,4.240734,0.000000,6.403321,2.749442,4.744344,0.035624,6.068116,6.467275,5.511436,...,1.364892,2.850993,2.851735,2.162065,3.385080,1.622092,1.134490,0.006404,0.933657,5.257708
592,ACH-000250,2.434946,0.000000,6.342743,2.670251,4.221382,0.188000,5.635487,6.935106,6.315050,...,1.571619,4.002847,2.876468,1.331562,3.287178,4.544399,0.664588,0.238360,1.049477,6.111812
601,ACH-001163,4.567831,0.717109,6.568405,2.108548,3.493045,0.000000,0.062590,4.931371,6.718019,...,0.525920,1.579861,2.416643,2.761636,3.264889,3.442847,1.926595,0.000000,0.052370,5.019751
624,ACH-002937,4.049474,0.000000,5.468169,1.715849,1.721871,0.000000,3.992007,5.012528,3.579011,...,0.141354,2.646695,0.850543,0.315075,2.948173,3.211263,0.187792,2.156982,0.787462,4.204720
626,ACH-000049,4.541372,0.000000,6.585768,2.313510,4.241695,0.036737,3.203485,6.644218,4.008012,...,1.489697,3.189926,2.962862,1.939813,3.120430,1.617186,1.385293,0.137837,0.379306,5.378630
801,ACH-000375,3.066017,0.022658,6.134213,2.556581,3.345856,0.000000,0.691986,3.806695,3.430285,...,1.529066,2.116661,3.054258,2.605814,3.284536,2.591727,1.418266,0.000000,0.198399,6.039105
829,ACH-001194,3.834003,0.000000,7.154575,2.629303,4.204704,0.047498,8.141841,6.075411,6.136677,...,1.644429,3.838619,3.621466,3.846323,3.753123,2.267796,0.354749,0.094541,0.327809,4.047163
885,ACH-000649,2.541101,0.000000,7.045421,2.138261,4.501223,0.000000,3.454355,6.997281,4.565597,...,1.218136,2.584573,3.275152,1.952009,4.400893,3.316573,0.748884,0.034909,0.700837,5.436328
939,ACH-000016,4.462530,0.000000,6.190176,2.318172,2.366722,0.000000,7.391630,6.127134,6.312458,...,1.625696,4.454794,1.676755,1.347989,3.788832,1.651646,0.936477,0.331444,1.168360,5.622740
977,ACH-000411,3.035960,0.000000,6.454929,2.434313,4.310231,0.000000,1.818912,6.588511,4.972454,...,1.714087,3.504455,2.160472,1.098325,4.082192,2.583801,0.532723,0.098670,0.701057,5.022159
981,ACH-000433,3.939010,0.000000,6.651957,2.487566,3.264751,0.000000,4.360554,6.050957,4.702525,...,1.366291,4.124568,1.527891,0.899019,4.858578,3.836116,1.007669,0.390630,0.412617,4.184883
990,ACH-002528,4.063839,0.000000,6.961091,2.288022,3.659205,0.000000,7.273460,6.552692,3.575772,...,0.249190,1.270152,1.215424,2.448497,4.343230,4.349401,0.384081,0.087563,0.782536,5.707061
1071,ACH-000533,3.175275,0.000000,6.697190,2.802456,3.420612,0.014715,0.138218,0.956856,3.498213,...,1.715212,2.378828,2.947904,2.160943,3.087658,1.839327,1.085567,0.000000,0.097415,5.953587
1074,ACH-000171,3.191177,0.000000,6.258807,2.713379,3.540337,0.038095,3.597412,6.505664,5.553812,...,2.009885,3.073637,2.655118,2.157008,4.164859,2.001881,1.316569,0.629548,0.295236,5.104639
1108,ACH-002435,4.596518,0.059017,6.063820,1.926554,2.792683,0.000000,4.200599,5.926379,3.330600,...,0.179638,0.825724,1.129520,1.025213,3.980336,3.538166,0.852596,0.545848,0.328835,4.393094
1134,ACH-000201,2.253672,0.000000,6.697774,3.615263,3.964814,0.041306,4.390282,6.809620,3.259505,...,1.563724,2.469042,2.771945,2.484187,3.929753,2.036982,2.588066,0.017309,0.331820,5.674156
1190,ACH-000189,2.520319,0.000000,6.577403,1.751986,2.670777,0.045931,1.059909,5.391799,3.401710,...,2.276241,3.490557,2.608987,1.599975,3.367157,4.776062,0.279853,0.662276,1.381040,5.447354
1303,ACH-000457,4.177009,0.000000,5.870838,2.320164,1.860438,0.000000,3.994715,6.174496,4.687296,...,1.225880,4.600609,1.884168,0.622730,3.785666,3.107457,0.115212,0.194370,1.239441,6.384782
1327,ACH-000159,3.989230,0.000000,7.383523,2.045974,3.583050,0.084943,5.451969,5.891820,3.414689,...,2.197353,3.409031,3.723406,1.744419,3.724443,3.670602,0.635966,1.424175,1.528351,5.255063
1328,ACH-000907,4.639684,0.000000,5.218677,1.917504,2.662178,0.000000,6.516077,6.600649,3.582580,...,1.195555,2.581088,2.187768,1.494907,2.490629,3.472020,0.371104,0.088182,0.585142,4.818283
1370,ACH-001423,4.054640,0.000000,6.496641,1.321697,2.407293,0.000000,4.529396,5.287927,3.588649,...,1.282707,0.451544,1.519240,1.126471,3.833669,2.707810,0.000000,0.000000,0.657620,4.553834
1380,ACH-000709,3.541515,0.000000,6.326893,1.817324,3.249456,0.030405,5.397334,6.330707,3.919102,...,0.901663,2.379712,1.690417,1.229822,3.035033,2.786299,0.283729,0.183704,0.818947,3.958472
1395,ACH-001210,2.823582,0.142811,6.537590,2.401669,3.732801,0.000000,0.157224,7.071344,3.551799,...,1.137910,1.853081,3.200498,2.998573,3.451936,1.861118,0.973986,0.017613,0.056726,6.448695
1398,ACH-003143,3.631745,0.000000,7.096272,2.439408,4.609134,0.124742,4.063555,6.553466,4.034154,...,1.670297,2.696321,2.941332,2.362128,4.941322,3.759912,1.320745,0.213080,0.701354,5.078994
1418,ACH-000385,3.913531,0.000000,7.034348,2.532482,4.246172,0.025451,6.599856,6.808655,5.895988,...,1.174381,3.497114,2.048515,1.058926,2.991719,2.479709,0.453419,0.065157,1.472592,5.682874
1475,ACH-000096,5.866584,0.139489,7.064139,3.675387,4.852289,0.000000,1.110129,5.796260,4.495088,...,1.521563,2.684704,2.837505,2.767600,4.716036,1.762340,1.286497,0.000000,0.171621,5.899860
1515,ACH-000495,4.501102,0.000000,7.321270,2.167024,3.523537,0.103276,5.749711,6.161293,3.992750,...,2.361704,2.598322,1.546719,0.001082,3.921198,3.813627,0.000000,0.016871,1.728090,5.508140
1546,ACH-000607,3.270397,0.000000,5.132334,3.061273,3.836914,0.056952,7.527946,5.372816,3.855003,...,1.861380,3.846082,2.649206,0.917535,3.543793,2.967836,1.970309,0.013987,0.169015,6.501856
1599,ACH-000555,3.988130,0.000000,6.612981,2.182603,3.399166,0.012235,6.071098,6.075595,5.605322,...,0.980630,3.117128,1.576783,1.220937,3.123290,2.575087,0.542748,0.043874,0.683524,5.224986
1604,ACH-001109,2.553267,0.000000,6.090392,2.534418,3.809219,0.000000,4.032551,6.588529,3.955341,...,2.227926,1.687625,2.736464,4.748896,3.709346,2.285518,1.461806,0.000000,1.729561,6.294615
1618,ACH-000272,3.295575,0.000000,6.199957,1.554623,3.600781,0.000000,0.731281,6.911008,3.868242,...,0.582828,2.513392,2.262698,1.369567,3.071888,1.867723,0.245502,0.023956,1.010887,5.041970
1621,ACH-000513,3.906919,0.000000,6.145351,2.023944,3.361970,0.048953,6.035745,4.242267,3.887545,...,1.253215,2.888463,0.907311,0.846078,2.131906,3.066950,0.173094,0.549701,0.318076,5.593939
1655,ACH-001532,4.122051,0.000000,6.197915,1.996595,2.276565,0.022155,0.000000,5.879787,4.215321,...,1.227341,2.437095,2.210763,1.054876,4.278632,2.245271,0.532086,0.000000,0.042490,4.881082
1672,ACH-001687,2.267383,0.000000,5.303817,1.154648,0.851320,0.014641,2.172036,4.969316,2.744084,...,0.095153,2.392246,0.451294,0.101833,2.162861,2.254047,0.000000,0.000000,0.080823,3.044840
1736,ACH-000046,3.802038,0.000000,6.084245,2.155208,3.685794,0.015700,1.011288,6.905977,4.790511,...,1.272190,2.829787,1.893028,2.107611,4.134287,2.757646,1.333000,0.151959,0.519793,5.337586

In [3]:
Crispr = pd.read_csv("../../../data/raw/depmap/CRISPRGeneEffect.csv")
Crispr

,Unnamed: 0,A1BG (1),A1CF (29974),A2M (2),A2ML1 (144568),A3GALT2 (127550),A4GALT (53947),A4GNT (51146),AAAS (8086),AACS (65985),...,ZWILCH (55055),ZWINT (11130),ZXDA (7789),ZXDB (158586),ZXDC (79364),ZYG11A (440590),ZYG11B (79699),ZYX (7791),ZZEF1 (23140),ZZZ3 (26009)
0,ACH-000015,-0.101628,0.033423,-0.084998,0.084588,-0.025752,0.014998,0.127182,-0.309637,0.087638,...,-0.329088,-0.271706,0.008982,0.066563,0.130267,0.044343,-0.182709,-0.107747,-0.135141,-0.236502
1,ACH-000045,0.071876,0.096220,0.030159,0.128536,0.010489,-0.062870,-0.067315,-0.472265,-0.116420,...,-0.149970,-0.610225,0.075264,0.227191,0.011966,-0.065919,-0.171262,0.023059,-0.206351,-0.458801
2,ACH-000094,0.100488,0.204729,0.111304,0.220877,0.022709,-0.009274,0.086337,-0.224036,0.082950,...,0.014893,-0.882753,-0.238187,0.024990,-0.128601,0.359461,-0.230729,0.231520,0.042054,-0.762764
3,ACH-000096,0.182435,-0.004316,-0.117120,0.135999,-0.169988,-0.200839,0.203096,-0.027621,0.013396,...,-0.312683,-0.410344,0.199127,0.067745,0.088566,0.175735,-0.163985,-0.366537,-0.122897,-0.104066
4,ACH-000099,-0.103127,0.075134,-0.071087,0.036089,-0.016140,-0.154740,0.024042,0.045064,-0.018520,...,-0.318896,-0.603687,0.034780,0.109159,0.150058,-0.031689,-0.422116,0.127047,-0.238114,-0.257072
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1181,ACH-002687,-0.063994,0.014906,0.119931,0.266804,0.012315,0.074110,0.006276,-0.374605,-0.065559,...,-0.262538,-0.878076,-0.022727,0.112161,0.163097,-0.017343,-0.267976,-0.140125,-0.033730,-0.738082
1182,ACH-002708,-0.008109,0.051431,0.048292,0.254607,-0.027347,-0.178628,0.223170,-0.797440,-0.155090,...,0.049700,-0.635168,-0.190640,0.138895,0.114770,-0.099998,-0.101318,-0.233697,0.040225,-0.449273
1183,ACH-002782,-0.019900,-0.034184,0.065603,0.128023,0.025150,-0.118020,0.021829,-0.324454,0.082824,...,0.005114,-0.270304,0.015133,0.045545,0.012244,-0.025254,-0.271036,-0.067795,-0.086425,-0.087778
1184,ACH-002785,-0.063686,-0.039207,0.025933,0.102223,-0.170395,0.061861,-0.044682,-0.347906,0.047099,...,0.081239,-0.157048,-0.024652,0.024075,-0.080117,-0.081808,-0.269077,-0.019338,-0.235562,-0.115628
1185,ACH-003012,-0.078337,0.057394,0.097809,0.236112,0.000839,-0.169590,0.085746,-0.535781,0.048535,...,-0.161418,-0.862785,-0.301187,0.084811,0.100871,0.192996,-0.227619,0.018162,-0.149161,-0.324425

In [8]:
Crispr.rename(columns={'Unnamed: 0':'ModelID'},inplace=True)
Crispr

,ModelID,A1BG (1),A1CF (29974),A2M (2),A2ML1 (144568),A3GALT2 (127550),A4GALT (53947),A4GNT (51146),AAAS (8086),AACS (65985),...,ZWILCH (55055),ZWINT (11130),ZXDA (7789),ZXDB (158586),ZXDC (79364),ZYG11A (440590),ZYG11B (79699),ZYX (7791),ZZEF1 (23140),ZZZ3 (26009)
0,ACH-000015,-0.101628,0.033423,-0.084998,0.084588,-0.025752,0.014998,0.127182,-0.309637,0.087638,...,-0.329088,-0.271706,0.008982,0.066563,0.130267,0.044343,-0.182709,-0.107747,-0.135141,-0.236502
1,ACH-000045,0.071876,0.096220,0.030159,0.128536,0.010489,-0.062870,-0.067315,-0.472265,-0.116420,...,-0.149970,-0.610225,0.075264,0.227191,0.011966,-0.065919,-0.171262,0.023059,-0.206351,-0.458801
2,ACH-000094,0.100488,0.204729,0.111304,0.220877,0.022709,-0.009274,0.086337,-0.224036,0.082950,...,0.014893,-0.882753,-0.238187,0.024990,-0.128601,0.359461,-0.230729,0.231520,0.042054,-0.762764
3,ACH-000096,0.182435,-0.004316,-0.117120,0.135999,-0.169988,-0.200839,0.203096,-0.027621,0.013396,...,-0.312683,-0.410344,0.199127,0.067745,0.088566,0.175735,-0.163985,-0.366537,-0.122897,-0.104066
4,ACH-000099,-0.103127,0.075134,-0.071087,0.036089,-0.016140,-0.154740,0.024042,0.045064,-0.018520,...,-0.318896,-0.603687,0.034780,0.109159,0.150058,-0.031689,-0.422116,0.127047,-0.238114,-0.257072
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1181,ACH-002687,-0.063994,0.014906,0.119931,0.266804,0.012315,0.074110,0.006276,-0.374605,-0.065559,...,-0.262538,-0.878076,-0.022727,0.112161,0.163097,-0.017343,-0.267976,-0.140125,-0.033730,-0.738082
1182,ACH-002708,-0.008109,0.051431,0.048292,0.254607,-0.027347,-0.178628,0.223170,-0.797440,-0.155090,...,0.049700,-0.635168,-0.190640,0.138895,0.114770,-0.099998,-0.101318,-0.233697,0.040225,-0.449273
1183,ACH-002782,-0.019900,-0.034184,0.065603,0.128023,0.025150,-0.118020,0.021829,-0.324454,0.082824,...,0.005114,-0.270304,0.015133,0.045545,0.012244,-0.025254,-0.271036,-0.067795,-0.086425,-0.087778
1184,ACH-002785,-0.063686,-0.039207,0.025933,0.102223,-0.170395,0.061861,-0.044682,-0.347906,0.047099,...,0.081239,-0.157048,-0.024652,0.024075,-0.080117,-0.081808,-0.269077,-0.019338,-0.235562,-0.115628
1185,ACH-003012,-0.078337,0.057394,0.097809,0.236112,0.000839,-0.169590,0.085746,-0.535781,0.048535,...,-0.161418,-0.862785,-0.301187,0.084811,0.100871,0.192996,-0.227619,0.018162,-0.149161,-0.324425

In [10]:
kidney_crispr = Crispr[Crispr["ModelID"].isin(kidney_id)]
print(kidney_crispr.shape[0])

35

In [21]:
Crispr.columns = ['ModelID'] + list(Crispr.columns[1:].str.split(" (", regex=False).str[0])
Crispr

,ModelID,A1BG,A1CF,A2M,A2ML1,A3GALT2,A4GALT,A4GNT,AAAS,AACS,...,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1,ZZZ3
0,ACH-000015,-0.101628,0.033423,-0.084998,0.084588,-0.025752,0.014998,0.127182,-0.309637,0.087638,...,-0.329088,-0.271706,0.008982,0.066563,0.130267,0.044343,-0.182709,-0.107747,-0.135141,-0.236502
1,ACH-000045,0.071876,0.096220,0.030159,0.128536,0.010489,-0.062870,-0.067315,-0.472265,-0.116420,...,-0.149970,-0.610225,0.075264,0.227191,0.011966,-0.065919,-0.171262,0.023059,-0.206351,-0.458801
2,ACH-000094,0.100488,0.204729,0.111304,0.220877,0.022709,-0.009274,0.086337,-0.224036,0.082950,...,0.014893,-0.882753,-0.238187,0.024990,-0.128601,0.359461,-0.230729,0.231520,0.042054,-0.762764
3,ACH-000096,0.182435,-0.004316,-0.117120,0.135999,-0.169988,-0.200839,0.203096,-0.027621,0.013396,...,-0.312683,-0.410344,0.199127,0.067745,0.088566,0.175735,-0.163985,-0.366537,-0.122897,-0.104066
4,ACH-000099,-0.103127,0.075134,-0.071087,0.036089,-0.016140,-0.154740,0.024042,0.045064,-0.018520,...,-0.318896,-0.603687,0.034780,0.109159,0.150058,-0.031689,-0.422116,0.127047,-0.238114,-0.257072
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1181,ACH-002687,-0.063994,0.014906,0.119931,0.266804,0.012315,0.074110,0.006276,-0.374605,-0.065559,...,-0.262538,-0.878076,-0.022727,0.112161,0.163097,-0.017343,-0.267976,-0.140125,-0.033730,-0.738082
1182,ACH-002708,-0.008109,0.051431,0.048292,0.254607,-0.027347,-0.178628,0.223170,-0.797440,-0.155090,...,0.049700,-0.635168,-0.190640,0.138895,0.114770,-0.099998,-0.101318,-0.233697,0.040225,-0.449273
1183,ACH-002782,-0.019900,-0.034184,0.065603,0.128023,0.025150,-0.118020,0.021829,-0.324454,0.082824,...,0.005114,-0.270304,0.015133,0.045545,0.012244,-0.025254,-0.271036,-0.067795,-0.086425,-0.087778
1184,ACH-002785,-0.063686,-0.039207,0.025933,0.102223,-0.170395,0.061861,-0.044682,-0.347906,0.047099,...,0.081239,-0.157048,-0.024652,0.024075,-0.080117,-0.081808,-0.269077,-0.019338,-0.235562,-0.115628
1185,ACH-003012,-0.078337,0.057394,0.097809,0.236112,0.000839,-0.169590,0.085746,-0.535781,0.048535,...,-0.161418,-0.862785,-0.301187,0.084811,0.100871,0.192996,-0.227619,0.018162,-0.149161,-0.324425

In [22]:
Crispr_lab = Crispr.columns[1:][Crispr.columns[1:].isin(ppi_genes)]
Crispr_lab.shape

(17863,)

In [23]:
Crispr_label = Crispr[['ModelID'] + list(Crispr_lab)]
Crispr_label.shape

(1186, 17864)

In [24]:
Crispr_label = Crispr_label[Crispr_label['ModelID'].isin(kidney_id)]

In [25]:
Crispr_label.to_csv("../data/processed/Crispr_labels_final.csv",index=False)

In [26]:
mutations = pd.read_csv("../data/raw/depmap/OmicsSomaticMutationsMatrixDamaging.csv")

In [27]:
mutations

,Unnamed: 0,SequencingID,ModelID,ModelConditionID,IsDefaultEntryForModel,IsDefaultEntryForMC,FAM87B (400728),LINC01128 (643837),LINC02593 (100130417),SAMD11 (148398),...,CTSLP8 (1518),ANKRD19P (138649),LINC00587 (414319),LINC02907 (157927),SSX13P (326341),SSX8P (280659),SOCS5P4 (100132415),KIF4CP (347363),GLRA4 (441509),TPTE2P4 (286573)
0,0,CDS-aN8PNg,ACH-000062,MC-000062-eiDD,Yes,Yes,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,CDS-1Zvqir,ACH-001949,MC-001949-eXWn,Yes,Yes,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,CDS-qjpRtt,ACH-002059,MC-002059-DNM1,Yes,Yes,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,CDS-bOBkBi,ACH-000402,MC-000402-iC8K,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,CDS-52aoJ0,ACH-000693,MC-000693-vUEr,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3016,3016,CDS-bkbrQT,ACH-000165,MC-000165-8cyy,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3017,3017,CDS-FCQOTY,ACH-000131,MC-000131-g6bE,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3018,3018,CDS-xxYsio,ACH-001310,MC-001310-xz7e,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3019,3019,CDS-po1c5u,ACH-001846,MC-001846-eTrK,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3020,3020,CDS-mPabL7,ACH-002018,MC-002018-Bkao,No,No,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [28]:
mutations = mutations[(mutations['IsDefaultEntryForModel'] == 'Yes') & (mutations['IsDefaultEntryForMC'] == 'Yes')]
mutations

,Unnamed: 0,SequencingID,ModelID,ModelConditionID,IsDefaultEntryForModel,IsDefaultEntryForMC,FAM87B (400728),LINC01128 (643837),LINC02593 (100130417),SAMD11 (148398),...,CTSLP8 (1518),ANKRD19P (138649),LINC00587 (414319),LINC02907 (157927),SSX13P (326341),SSX8P (280659),SOCS5P4 (100132415),KIF4CP (347363),GLRA4 (441509),TPTE2P4 (286573)
0,0,CDS-aN8PNg,ACH-000062,MC-000062-eiDD,Yes,Yes,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,CDS-1Zvqir,ACH-001949,MC-001949-eXWn,Yes,Yes,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,CDS-qjpRtt,ACH-002059,MC-002059-DNM1,Yes,Yes,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,CDS-bOBkBi,ACH-000402,MC-000402-iC8K,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,CDS-52aoJ0,ACH-000693,MC-000693-vUEr,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3015,3015,CDS-2W4vBy,ACH-000134,MC-000134-Xj1k,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3016,3016,CDS-bkbrQT,ACH-000165,MC-000165-8cyy,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3017,3017,CDS-FCQOTY,ACH-000131,MC-000131-g6bE,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3018,3018,CDS-xxYsio,ACH-001310,MC-001310-xz7e,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3019,3019,CDS-po1c5u,ACH-001846,MC-001846-eTrK,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [30]:
mutations = mutations[mutations['ModelID'].isin(kidney_id)]
mutations

,Unnamed: 0,SequencingID,ModelID,ModelConditionID,IsDefaultEntryForModel,IsDefaultEntryForMC,FAM87B (400728),LINC01128 (643837),LINC02593 (100130417),SAMD11 (148398),...,CTSLP8 (1518),ANKRD19P (138649),LINC00587 (414319),LINC02907 (157927),SSX13P (326341),SSX8P (280659),SOCS5P4 (100132415),KIF4CP (347363),GLRA4 (441509),TPTE2P4 (286573)
71,71,CDS-2YtzZh,ACH-001398,MC-001398-XBHi,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
191,191,CDS-2DkVpG,ACH-000250,MC-000250-3qw8,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
211,211,CDS-oY6Tvj,ACH-000684,MC-000684-OsUg,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
234,234,CDS-flEsqI,ACH-000457,MC-000457-BEt0,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
249,249,CDS-lxzoAp,ACH-000246,MC-000246-NnuW,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2926,2926,CDS-YR6sA3,ACH-002187,MC-002187-kPXJ,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2982,2982,CDS-bT5QTI,ACH-001163,MC-001163-vV3z,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2991,2991,CDS-Cm1kuD,ACH-002151,MC-002151-ZdkB,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3008,3008,CDS-FfB0Fb,ACH-002937,MC-002937-gD8Q,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3018,3018,CDS-xxYsio,ACH-001310,MC-001310-xz7e,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [31]:
mutations.columns[:7]

Index(['Unnamed: 0', 'SequencingID', 'ModelID', 'ModelConditionID',
       'IsDefaultEntryForModel', 'IsDefaultEntryForMC', 'FAM87B (400728)'],
      dtype='str')

In [33]:
mutations.columns = list(mutations.columns[:6]) + list(mutations.columns[6:].str.split(" (", regex=False).str[0])
mutations

,Unnamed: 0,SequencingID,ModelID,ModelConditionID,IsDefaultEntryForModel,IsDefaultEntryForMC,FAM87B,LINC01128,LINC02593,SAMD11,...,CTSLP8,ANKRD19P,LINC00587,LINC02907,SSX13P,SSX8P,SOCS5P4,KIF4CP,GLRA4,TPTE2P4
71,71,CDS-2YtzZh,ACH-001398,MC-001398-XBHi,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
191,191,CDS-2DkVpG,ACH-000250,MC-000250-3qw8,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
211,211,CDS-oY6Tvj,ACH-000684,MC-000684-OsUg,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
234,234,CDS-flEsqI,ACH-000457,MC-000457-BEt0,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
249,249,CDS-lxzoAp,ACH-000246,MC-000246-NnuW,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2926,2926,CDS-YR6sA3,ACH-002187,MC-002187-kPXJ,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2982,2982,CDS-bT5QTI,ACH-001163,MC-001163-vV3z,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2991,2991,CDS-Cm1kuD,ACH-002151,MC-002151-ZdkB,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3008,3008,CDS-FfB0Fb,ACH-002937,MC-002937-gD8Q,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3018,3018,CDS-xxYsio,ACH-001310,MC-001310-xz7e,Yes,Yes,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [38]:
muta_cols = mutations.columns[6:][mutations.columns[6:].isin(ppi_genes)]
mutations= mutations[['ModelID'] + list(muta_cols)]

In [39]:
mutations

,ModelID,SAMD11,NOC2L,KLHL17,PLEKHN1,PERM1,HES4,ISG15,AGRN,C1orf159,...,NLGN4Y,KDM5D,PRORY,IFT25,PCBD1,CEBPZOS,VPREB3,SCOC,SMIM3,LSM5
71,ACH-001398,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
191,ACH-000250,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
211,ACH-000684,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
234,ACH-000457,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
249,ACH-000246,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2926,ACH-002187,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2982,ACH-001163,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2991,ACH-002151,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3008,ACH-002937,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3018,ACH-001310,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [40]:
mutations.to_csv("../data/processed/mutations_final.csv",index = False)

In [40]:
mutations

,ModelID,FAM87B (400728),LINC01128 (643837),LINC02593 (100130417),SAMD11 (148398),NOC2L (26155),KLHL17 (339451),PLEKHN1 (84069),PERM1 (84808),HES4 (57801),...,CTSLP8 (1518),ANKRD19P (138649),LINC00587 (414319),LINC02907 (157927),SSX13P (326341),SSX8P (280659),SOCS5P4 (100132415),KIF4CP (347363),GLRA4 (441509),TPTE2P4 (286573)
71,ACH-001398,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
191,ACH-000250,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
211,ACH-000684,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
234,ACH-000457,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
249,ACH-000246,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2926,ACH-002187,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2982,ACH-001163,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2991,ACH-002151,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3008,ACH-002937,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3018,ACH-001310,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [42]:
mutations_cols = mutations.columns[1:][mutations.columns[1:].isin(ppi_genes)]
mutations = mutations[['ModelID'] + list(mutations_cols)]

In [42]:
mutations

,ModelID,SAMD11,NOC2L,KLHL17,PLEKHN1,PERM1,HES4,ISG15,AGRN,C1orf159,...,NLGN4Y,KDM5D,PRORY,IFT25,PCBD1,CEBPZOS,VPREB3,SCOC,SMIM3,LSM5
71,ACH-001398,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
191,ACH-000250,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
211,ACH-000684,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
234,ACH-000457,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
249,ACH-000246,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2926,ACH-002187,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2982,ACH-001163,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2991,ACH-002151,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3008,ACH-002937,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3018,ACH-001310,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [45]:
missing = set(ppi_genes) - set(mutations.columns[1:])
missing

{'ZNF286A',
 'SPAG11A',
 'SPATA31C1',
 'SCGB1A1',
 'SPATA31A7',
 'PTGDR2',
 'OR5C1',
 'MRPS21',
 'SFXN5',
 'BANF1',
 'NCF1',
 'FUNDC1',
 'FBXO36',
 'TRIM43',
 'ZNF705D',
 'CSNK1E',
 'FAM25G',
 'RSPO1',
 'VKORC1',
 'RNF113B',
 'PDZK1',
 'OR51B4',
 'DEFB130A',
 'TMEM216',
 'SPANXA2',
 'XAGE1A',
 'OST4',
 'PGA4',
 'DEFA1',
 'SFTA2',
 'ELOF1',
 'CLN8',
 'SNRPD2',
 'NDUFB7',
 'SYT15',
 'SLC13A2',
 'PCP4L1',
 'ACP1',
 'FKBP14',
 'TGIF2LY',
 'GPHB5',
 'FRG2',
 'SUPT4H1',
 'GOLGA6A',
 'NUDT4',
 'FSAF1',
 'LAIR2',
 'NPY4R',
 'AMY1C',
 'CT45A6',
 'C21orf140',
 'AGAP4',
 'RBX1',
 'TMEM225B',
 'RPL18',
 'WFDC6',
 'NME2',
 'MRGBP',
 'GOLGA6L1',
 'GOLGA6D',
 'MRPL32',
 'PRAMEF5',
 'GPR89B',
 'GGACT',
 'DCTN5',
 'SMIM1',
 'POTEB2',
 'TXNL4B',
 'MRGPRX3',
 'PTTG2',
 'ANGPTL8',
 'ZNF740',
 'ENOPH1',
 'CSH2',
 'NUDT4B',
 'SPRR2E',
 'C1QTNF1',
 'RPRML',
 'TNFRSF10C',
 'INO80C',
 'TRIM16',
 'SMIM10L2B',
 'S100A6',
 'COLEC11',
 'NDUFB3',
 'PTPN20',
 'STRC',
 'GAGE2E',
 'MALL',
 'ETFA',
 'SPATA31A3',
 'ACTR3C',
 'RAB17',
 'CHCHD1',
 'TOMM6',
 'SYCN',
 'OPN1LW',
 'CNN3',
 'NUTM2D',
 'FCGR3B',
 'SLURP1',
 'COA1',
 'YPEL1',
 'OR13C3',
 'SNU13',
 'EIF1B',
 'CD59',
 'PLEKHJ1',
 'GTF2H4',
 'KRTAP1-5',
 'INSL5',
 'GPR143',
 'HSPA1B',
 'ARF4',
 'GTF2IRD2',
 'CMTM7',
 'CXCL12',
 'GOLGA8R',
 'PRODH',
 'DEFB107B',
 'EEF1E1',
 'C18orf32',
 'CNIH2',
 'ABHD10',
 'MT-ATP8',
 'KRTAP10-3',
 'KRTAP7-1',
 'NDUFB6',
 'ARPP19',
 'S100A4',
 'TMEM141',
 'SRGAP2C',
 'ZNF322',
 'DAZ3',
 'TUBB2B',
 'CT45A3',
 'GNRH1',
 'OR4F4',
 'BBLN',
 'ARF3',
 'TNFRSF13C',
 'OR1G1',
 'CDRT15',
 'KCNE3',
 'TAS2R20',
 'KIAA1143',
 'DESI2',
 'POTEG',
 'RSPH10B2',
 'MBNL3',
 'ARL4A',
 'C4B',
 'XXYLT1',
 'IGFL3',
 'ABRACL',
 'CLEC4D',
 'SSU72',
 'THAP12',
 'RSL24D1',
 'PPP1R3D',
 'RWDD2A',
 'ARL6IP5',
 'TRIM43B',
 'RDH12',
 'PKIG',
 'UPK3BL1',
 'S100A14',
 'DEFB4B',
 'SPATA31A5',
 'SF3B5',
 'GOLGA8N',
 'TXNDC15',
 'HIGD1C',
 'EI24',
 'MRPL3',
 'LAMTOR4',
 'PSMG4',
 'C1orf210',
 'BRI3',
 'RAB40AL',
 'GARIN5B',
 'KIAA2013',
 'TOMM5',
 'MAP2K2',
 'HSFX1',
 'AMY1A',
 'KRTAP19-1',
 'MYL9',
 'LRRC37A3',
 'CT45A9',
 'TMEM212',
 'SMIM10L2A',
 'SSX4B',
 'AGAP5',
 'NBPF11',
 'IKBKG',
 'SPANXC',
 'GTF2IRD2B',
 'RAB3B',
 'IGFL1',
 'GOLGA8J',
 'TSSK4',
 'RAB28',
 'NPIPA1',
 'MRO',
 'PTGES',
 'RGPD1',
 'TMEM256',
 'GAL',
 'RAB15',
 'TMEM203',
 'PRY',
 'IL17D',
 'DPH3',
 'NUDC',
 'KCNE1',
 'BCL7B',
 'OR2V2',
 'PIN1',
 'NIP7',
 'SAMD13',
 'C7orf33',
 'CIAO2B',
 'LRTM2',
 'PMCH',
 'S100A13',
 'NBPF20',
 'TM2D2',
 'OR10A3',
 'LCE3D',
 'GABARAPL1',
 'PDHB',
 'MAPDA',
 'OR2A4',
 'ZBTB42',
 'CD8B',
 'MAGEA9B',
 'KRT86',
 'OR2T3',
 'THTPA',
 'NICOL1',
 'SLC35B2',
 'H2BC12L',
 'TMEM240',
 'HSPB9',
 'ELMOD3',
 'USP17L23',
 'RPS20',
 'CD24',
 'DNAJC30',
 'NOMO3',
 'BBIP1',
 'FOXD4L6',
 'GUK1',
 'NAT9',
 'SHISA2',
 'SSR4',
 'PSCA',
 'TNFAIP8L1',
 'SHLD1',
 'NDUFA4',
 'MZT1',
 'TBC1D3B',
 'LCN2',
 'MRPS11',
 'NXF2',
 'TIMM13',
 'EVA1B',
 'FCF1',
 'CLDN19',
 'GAGE12D',
 'TMEM98',
 'SS18L2',
 'H2AC20',
 'SPINK4',
 'CLDN8',
 'PGAM1',
 'MT1F',
 'DAND5',
 'SMIM26',
 'CENPA',
 'SPRR1B',
 'SPATA9',
 'WDR83OS',
 'KRTAP9-7',
 'SMIM8',
 'ATP5PO',
 'PLA2G2A',
 'DEFB135',
 'GABPB2',
 'LSMEM2',
 'UPK3BL2',
 'CALHM2',
 'GOLGA8O',
 'PRR20E',
 'SPRR2B',
 'POU4F3',
 'NDUFB2',
 'RAB41',
 'C5orf58',
 'SCRN1',
 'NBPF19',
 'MOGAT1',
 'NBPF6',
 'BACC1',
 'SSX2B',
 'AGRP',
 'FCGR3A',
 'FAM219B',
 'CAPZA1',
 'CCZ1B',
 'NXT1',
 'TMEM220',
 'DMAC1',
 'MUC1',
 'OR52N4',
 'ATP5F1E',
 'NUTM2B',
 'HIGD1A',
 'UBTFL1',
 'PRAMEF13',
 'NOTCH2NLA',
 'USP17L1',
 'LIMS4',
 'FAM174B',
 'TMEM230',
 'NUDT14',
 'IL22',
 'RBMY1E',
 'NUBPL',
 'DEFB130B',
 'SULT1A3',
 'VPS36',
 'LRRC37A',
 'ANXA2R',
 'OR1D4',
 'SNX3',
 'TBC1D26',
 'MRTO4',
 'CT45A1',
 'POM121C',
 'LGALS9C',
 'CXCL10',
 'ATP6V1E2',
 'AQP12B',
 'CHD9NB',
 'MIF4GD',
 'GAGE13',
 'CSDC2',
 'ZGLP1',
 'SMAD1',
 'GRAPL',
 'H3-7',
 'RABL2A',
 'VHLL',
 'LCE3C',
 'CT47A8',
 'DUSP3',
 'NPIPB6',
 'TNFAIP8L3',
 'VTI1A',
 'USP17L17',
 'OR1D5',
 'PPCDC',
 'TEN1',
 'FAM86B2',
 'CD300H',
 'VAPB',
 'CNTNAP3',
 'SIAH3',
 'TMEM241',
 'RPL8',
 'NPIPB13',
 'DEXI',
 'SNRPD1',
 'TOMM20',
 'FAM153A',
 'ENKD1',
 'ARL6IP1',
 'CSF2',
 'RTP4',
 'PPP1R27',
 'MT-ND2',
 'FAM25C',
 'HSD17B10',
 'CISD2',
 'NEU1',
 'KDELR2',
 'APOC1',
 'SEPTIN2',
 'KRTAP3-2',
 'SDF2L1',
 'EIF4EBP2',
 'FXN',
 'NBPF10',
 'FNDC8',
 'KRTCAP3',
 'RASA4B',
 'SCGB1C1',
 'PTRHD1',
 'APLN',
 'NDUFB1',
 'LRRC58',
 'PIRT',
 'ARL8B',
 'CKMT1A',
 'SLC66A2',
 'PGLYRP1',
 'TMEM167B',
 'LRRC37A2',
 'RPL15',
 'CRYGC',
 'RTP1',
 'DYNLRB2',
 'GNG13',
 'CSTA',
 'HBZ',
 'GMFG',
 'DDTL',
 'VIPR1',
 'SCIMP',
 'HS6ST1',
 'NDUFAB1',
 'SYNGR2',
 'RPL18A',
 'SRGAP2B',
 'ABHD8',
 'CAV1',
 'LCN12',
 'SLBP',
 'H2AB1',
 'PPP1R11',
 'PEX39',
 'NUTM2F',
 'MAGEA3',
 'NANOS1',
 'RNASE8',
 'PDHA1',
 'CLEC2L',
 'RGPD2',
 'TP53TG3E',
 'PPIAL4G',
 'SPRYD4',
 'TIMM10',
 'WFDC9',
 'RAB18',
 'DPH5',
 'CXorf51A',
 'POM121',
 'TRIM74',
 'FOXO3B',
 'TRIM49',
 'TLCD3A',
 'UTS2',
 'NPIPB11',
 'RGPD6',
 'BTBD6',
 'TRIM49C',
 'SCO1',
 'INSL4',
 'HEPN1',
 'SETD9',
 'ZSWIM7',
 'PRSS3',
 'SMN2',
 'CT45A10',
 'KRTAP19-2',
 'PWP2',
 'HMGN3',
 'SPDYE2B',
 'USP17L18',
 'SNRNP25',
 'AK6',
 'MAD2L1BP',
 'RNF26',
 'CD81',
 'F8A3',
 'TSPO2',
 'APOC3',
 'HSPA1A',
 'SLN',
 'PPP1R14A',
 'CYB5B',
 'OR1L1',
 'TRAPPC5',
 'NME4',
 'OR4M2',
 'NPIPB3',
 'LIMS1',
 'GOLGA6L10',
 'CXCL3',
 'NOMO1',
 'FOXD4L1',
 'SDR42E1',
 'IFNA6',
 'SLC31A2',
 'GNG4',
 'POTEH',
 'RHOXF2',
 'FCGR1A',
 'NHLRC4',
 'SFTPC',
 'PGA3',
 'MRPL23',
 'TACSTD2',
 'BRD3OS',
 'PRAMEF10',
 'PABPC1L2B',
 'ZNG1A',
 'PRCD',
 'USP17L25',
 'SLC39A9',
 'DGCR6',
 'ANAPC15',
 'KRTAP12-1',
 'OR4F3',
 'TSPY10',
 'TBC1D28',
 'GTF2E1',
 'NCBP2',
 'MGST3',
 'RNPS1',
 'CFAP97D1',
 'GAGE12G',
 'USP17L4',
 'VCY1B',
 'SLC37A4',
 'CDC42EP2',
 'MAPK1IP1L',
 'RRAS2',
 'ACER3',
 'ACSM2A',
 'JAGN1',
 'KLRD1',
 'PNRC2',
 'FAM156A',
 'MRGPRD',
 'USP17L7',
 'NDUFAF2',
 'CFAP107',
 'NBPF26',
 'RPL23A',
 'SUV39H1',
 'PCLAF',
 'GOLGA6L9',
 'LCE1E',
 'CTAGE6',
 'OPN1MW',
 'PF4V1',
 'H2BW1',
 'SF3B6',
 'ASB12',
 'TOMM20L',
 'SPRN',
 'RPL7A',
 'TEX13B',
 'ZFY',
 'EDN2',
 'ATP5MC2',
 'C2orf68',
 'GLIPR2',
 'CST9',
 'MT1A',
 'LGALS7',
 'APOBEC4',
 'PRAMEF25',
 'C8orf82',
 'EIF1AY',
 'YPEL4',
 'NDUFC1',
 'TIMM17A',
 'NBPF9',
 'TMEM9',
 'DMRTC1B',
 'POLR2J',
 'CFC1',
 'RGPD3',
 'RPL34',
 'SDHAF1',
 'RPLP1',
 'TSPY2',
 'RND1',
 'TMEM70',
 'LAMTOR5',
 'OR3A1',
 'PRR20C',
 'NUDT16L1',
 'RPP21',
 'ZNG1E',
 'TMEM14C',
 'CYB561D1',
 'ZNF706',
 'CENPS',
 'UFD1',
 'CT45A8',
 'AMY1B',
 'AP1S1',
 'SPAG11B',
 'SPP2',
 'SDHAF2',
 'SHISA4',
 'TIMM23',
 'FAM153B',
 'CRABP1',
 'H3C15',
 'ANKRD20A1',
 'HSFY2',
 'TRABD',
 'FBXW10B',
 'CLEC4C',
 'SVBP',
 'BAG2',
 'LCE3A',
 'MRFAP1L2',
 'MDK',
 'TBC1D3C',
 'CHRAC1',
 'PPIAL4A',
 'POTEB',
 'CST7',
 'NANOS3',
 'NRARP',
 'DUX4',
 'EIF4EBP1',
 'C3AR1',
 'RAN',
 'FKBP1B',
 'CRB3',
 'OSR2',
 'TPSAB1',
 'HESX1',
 'CFC1B',
 'EDDM3A',
 'OR2T2',
 'PAFAH1B3',
 'TMEM18',
 'KRTAP21-2',
 'NOMO2',
 'BNIP3',
 'ATAT1',
 'MRPS17',
 'ANXA8',
 'SIK1',
 'PRR20B',
 'PACRGL',
 'CIMIP5',
 'ARMS2',
 'H2AB2',
 'NBPF14',
 'ZFAND2B',
 'IFNA14',
 'RBP4',
 'CDC14C',
 'MIS18A',
 'TRIM64B',
 'CCL7',
 'PEA15',
 'SAMTOR',
 'CAAP1',
 'CENPM',
 'FBXW2',
 'TMEM33',
 'CXorf51B',
 'POMZP3',
 'HIKESHI',
 'RPL35A',
 'TRIM64',
 'NDUFAF8',
 'ASF1B',
 'HRAS',
 'EXOSC5',
 'FOXD4',
 'NFAM1',
 'RIT1',
 'OR3A2',
 'PPIL1',
 'KIR2DS4',
 'USP17L12',
 'HDDC3',
 'ACER2',
 'MIS12',
 'H2AZ1',
 'RPL41',
 'CTAGE15',
 'LGALS9B',
 'BOLA2B',
 'NUTM2G',
 'PPIAL4F',
 'SERF1B',
 'ARL17A',
 'SULT1A4',
 'KRTAP19-3',
 'RHOXF2B',
 'RASA4',
 'GOLGA8K',
 'DLX2',
 'ZNF658',
 'SNRNP27',
 'ACSM2B',
 'ZNG1B',
 'CAMK2N1',
 'SMIM5',
 'GGTLC3',
 'OAZ3',
 'LSM3',
 'RAB9B',
 'SPANXB1',
 'ASPN',
 'MANSC4',
 'ARL4C',
 'SPINK6',
 'DEFB104A',
 'ZNF439',
 'PLAC9',
 'CPAP',
 'RHOXF1',
 'NPIPA3',
 'PLA2G12B',
 'SPATA24',
 'C10orf62',
 'NBPF15',
 'SHISA3',
 'MYLK4',
 'RGPD8',
 'DCTN3',
 'OXCT2',
 'ATOX1',
 'OR10G3',
 'FABP4',
 'NPIPA7',
 'GOLGA8M',
 'TEX19',
 'PPP1R1A',
 'OR2T35',
 'PROCR',
 'NOTCH2NLC',
 'ZNG1C',
 'SPATA31D3',
 'TSPY1',
 'SPIN2B',
 'AP1S3',
 'UBE2L5',
 'C4orf46',
 'DEFA5',
 'LRRC10',
 'MTNR1A',
 'CCDC144A',
 'IFNL4',
 'MAGEA2',
 'NANOGP8',
 'DTX2',
 'ZC3H11C',
 'OR2AT4',
 'DEFB109B',
 'CCDC127',
 'CCL5',
 'RHCE',
 'RIMBP3B',
 'TGIF2LX',
 'SHLD2',
 'ZNF213',
 'CD300LF',
 'GOLGA6C',
 'EIF3F',
 'SYT15B',
 'HAND1',
 'PRAMEF4',
 'ASB8',
 'RBMY1A1',
 'RABL2B',
 'RAP2A',
 'RNF227',
 'PRR23D1',
 'PRAMEF2',
 'SEC22B',
 'CSRP1',
 'TPD52L2',
 'CMTM8',
 'TIMM23B',
 'METRN',
 'MAGED4',
 'CKS1B',
 'FBXL12',
 'FNDC4',
 'LCN8',
 'RPL36AL',
 'MDH2',
 'POLR2J3',
 'MT1X',
 'PIGY',
 'HSBP1',
 'TIRAP',
 'RAMP2',
 'SPANXN5',
 'MAGEA6',
 'WASHC2C',
 'TICAM2',
 'RPH3AL',
 'PGM5',
 'SPDYE16',
 'NUTM2A',
 'SNRPE',
 'REEP3',
 'CATSPERZ',
 'DAZ2',
 'NSF',
 'SLC35D2',
 'EEF1AKMT1',
 'TOMM40L',
 'OXTR',
 'AP3S1',
 'CRKL',
 'CLEC6A',
 'NPFF',
 'KDELR1',
 'P2RY14',
 'PTGER2',
 'HSPA6',
 'POLR3D',
 'AIMP2',
 'WASHC2A',
 'FXYD2',
 'HSD17B7',
 'MANBAL',
 'SYCE2',
 'POTEE',
 'SERPINB9',
 'PRELID3A',
 'RPA2',
 'CHCHD2',
 'GOLGA6B',
 'PCDH11Y',
 'MGMT',
 'APOE',
 'ANXA8L1',
 'PLA2G2F',
 'DNAJC15',
 'SLC25A20',
 'LEPROT',
 'SRSF9',
 'TMEM229B',
 'TMEM204',
 'KRTAP2-2',
 'PERP',
 'TSPO',
 'WASHC1',
 'CYSLTR2',
 'SMIM14',
 'C2orf72',
 'GATD3',
 'PGRMC2',
 'UBE2A',
 'HIGD2A',
 'AGAP9',
 'CXCL11',
 'RPL31',
 'KRTAP22-1',
 'USP18',
 'FAM89A',
 'ATP6V0E1',
 'GOLGA8Q',
 'INS',
 'TCP11X2',
 'UBA52',
 'ZNG1F',
 'S100G',
 'MYL12B',
 'CBS',
 'GSTT2',
 'GPATCH4',
 'VTCN1',
 'PTDSS2',
 'PRR23D2',
 'TXN',
 'TBC1D3H',
 'CHST14',
 'OR4F17',
 'RPL36A',
 'S100P',
 'PNMA6A',
 'AGAP6',
 'TOMM7',
 'SMIM2',
 'USP17L3',
 'CCL13',
 'RAMP1',
 'EIF3CL',
 'SGCG',
 'CCDC106',
 'CHRFAM7A',
 'OR51G1',
 'CDY1B',
 'TMEM107',
 'SPDYE6',
 'TSPY3',
 'NBPF8',
 'POTEB3',
 'RNASE13',
 'RHD',
 'DNLZ',
 'FOXD4L3',
 'FBXO9',
 'PGK1',
 'COX8C',
 'DAZ4',
 'DPCD',
 'PRR20D',
 'TIPIN',
 'CT45A2',
 'CFAP20',
 'POTEF',
 'MT-ATP6',
 'TCEAL7',
 'TVP23C',
 'TTC9B',
 'SRARP',
 'DESI1',
 'FZD4',
 'GPR17',
 'NPIPB5',
 'C4A',
 'KANTR',
 'FIBIN',
 'KRTAP23-1',
 'TPSB2',
 'NAA40',
 'IFITM2',
 'TVP23B',
 'MUSTN1',
 'RCAN2',
 'PROK1',
 'LCN9',
 'FAM89B',
 'PSMA7',
 'GH1',
 'CATSPER2',
 'RBM8A',
 'PRAMEF8',
 'DUSP18',
 'MTX2',
 'RPS4Y2',
 'C1QBP',
 'YPEL2',
 'SLX1A',
 'RAB7B',
 'H2BC18',
 'DEFB114',
 'VMA21',
 'NXT2',
 'PHPT1',
 'EEIG1',
 'ARLN',
 'COA7',
 'NOP10',
 'NAT8',
 'SMR3A',
 'CALCA',
 'PARP16',
 'NQO1',
 'RAB11B',
 'U2AF1',
 'TAS2R40',
 'SPATA45',
 'TPBGL',
 'GOLGA8B',
 'CLEC18C',
 'TMEM222',
 'GOLGA8A',
 'ATP6V0E2',
 'SCGB1C2',
 'SUMO4',
 'USP17L8',
 'MRPL36',
 'H1-10',
 'OAZ1',
 'POPDC1',
 'RNF122',
 'S100A5',
 'PDE7B',
 'CNTNAP3B',
 'RPL27',
 'CIAPIN1',
 'CDK2',
 'GAGE1',
 'NRGN',
 'NABP1',
 'HNRNPCL3',
 'SMIM11',
 'ERICH4',
 'MAEA',
 'RBMY1D',
 'NME3',
 'ACTR10',
 'RNF24',
 'ACSM5',
 'MC4R',
 'SCGB2B2',
 'SLC7A6OS',
 'USP17L5',
 'ARHGEF35',
 ...}